-- Seeded from the original static pages; values are unchanged.

INSERT INTO public.site_texts (key, lang, value, page, kind) VALUES
('t_11xu9gz7ozwfy', 'tr', 'Designed By', 'index', 'text'),
('t_11xu9gz7ozwfy', 'en', 'Designed By', 'index', 'text'),
('t_172rmfkwe7wq6', 'tr', 'Aurazone', 'index', 'text'),
('t_172rmfkwe7wq6', 'en', 'Aurazone', 'index', 'text'),
('t_07uchwwd5l76i', 'tr', '© 2026 Dr. Taha Demir - Tüm hakları saklıdır.', 'index', 'text'),
('t_07uchwwd5l76i', 'en', '© 2026 Dr. Taha Demir - All rights reserved.', 'index', 'text'),
('t_eh747c1ntqk12', 'tr', 'Cumartesi', 'index', 'text'),
('t_eh747c1ntqk12', 'en', 'Saturday', 'index', 'text'),
('t_11gqbwc1omi5bm', 'tr', '10:00 - 14:00', 'index', 'text'),
('t_11gqbwc1omi5bm', 'en', '10:00 - 14:00', 'index', 'text'),
('t_1lzpyc4s1mhwh', 'tr', 'Ataköy Towers, A Blok, Kat 4, No 79, Bakırköy/İstanbul', 'index', 'text'),
('t_1lzpyc4s1mhwh', 'en', 'Ataköy Towers, A Blok, Kat 4, No 79, Bakırköy/İstanbul', 'index', 'text'),
('t_1k2dehqhrwxn9', 'tr', 'Hafta Sonu', 'index', 'text'),
('t_1k2dehqhrwxn9', 'en', 'Weekend', 'index', 'text'),
('t_1r8p68rk324o9', 'tr', 'Pazartesi - Cuma', 'index', 'text'),
('t_1r8p68rk324o9', 'en', 'Monday - Friday', 'index', 'text'),
('t_wnhsp410b5x1i', 'tr', '10:00 - 18:00', 'index', 'text'),
('t_wnhsp410b5x1i', 'en', '10:00 - 18:00', 'index', 'text'),
('t_8ja7gv1dwldbr', 'tr', 'Hafta İçi', 'index', 'text'),
('t_8ja7gv1dwldbr', 'en', 'Weekdays', 'index', 'text'),
('t_15paadk15gplei', 'tr', 'Çalışma Bilgileri', 'index', 'text'),
('t_15paadk15gplei', 'en', 'Work Information', 'index', 'text'),
('t_uwk15517b5w4x', 'tr', 'Anasayfa', 'index', 'text'),
('t_uwk15517b5w4x', 'en', 'Home', 'index', 'text'),
('t_0l6orsjf0855m', 'tr', 'Galeri', 'index', 'text'),
('t_0l6orsjf0855m', 'en', 'Gallery', 'index', 'text'),
('t_1gxhn9j15m8bjl', 'tr', 'Tedaviler', 'index', 'text'),
('t_1gxhn9j15m8bjl', 'en', 'Treatments', 'index', 'text'),
('t_a6nw6e1yexc5u', 'tr', 'İletişim', 'index', 'text'),
('t_a6nw6e1yexc5u', 'en', 'Contact', 'index', 'text'),
('t_0xls2mpzqvauh', 'tr', 'Hakkımda', 'index', 'text'),
('t_0xls2mpzqvauh', 'en', 'About Me', 'index', 'text'),
('t_1f6x4b4fy7q02', 'tr', 'Hızlı Erişim', 'index', 'text'),
('t_1f6x4b4fy7q02', 'en', 'Quick Access', 'index', 'text'),
('t_1evew481oksr5i', 'tr', 'Çocuk Ortopedisi', 'index', 'text'),
('t_1evew481oksr5i', 'en', 'Pediatric Orthopedics', 'index', 'text'),
('t_1nrrodw1kj875j', 'tr', 'Deformite Cerrahisi', 'index', 'text'),
('t_1nrrodw1kj875j', 'en', 'Deformity Surgery', 'index', 'text'),
('t_1ir5w5e1klyhua', 'tr', 'Omurga Cerrahisi', 'index', 'text'),
('t_1ir5w5e1klyhua', 'en', 'Spine Surgery', 'index', 'text'),
('t_159iwjtftn6p9', 'tr', 'Omuz ve Dirsek Cerrahisi', 'index', 'text'),
('t_159iwjtftn6p9', 'en', 'Shoulder and Elbow Surgery', 'index', 'text'),
('t_1k65hqc1w7rg4f', 'tr', 'Artroskopik Cerrahi', 'index', 'text'),
('t_1k65hqc1w7rg4f', 'en', 'Arthroscopic Surgery', 'index', 'text'),
('t_zp8w1p1jonm2k', 'tr', 'Diz ve Kalça Cerrahisi', 'index', 'text'),
('t_zp8w1p1jonm2k', 'en', 'Knee and Hip Surgery', 'index', 'text'),
('t_0zbplol4kc23y', 'tr', 'Eklem Protez Cerrahisi', 'index', 'text'),
('t_0zbplol4kc23y', 'en', 'Joint Replacement Surgery', 'index', 'text'),
('t_mw89wa16hfvhu', 'tr', 'Tedavilerimiz', 'index', 'text'),
('t_mw89wa16hfvhu', 'en', 'Our Treatments', 'index', 'text'),
('t_02oexkpyyjr37', 'tr', 'info@drtahademir.com', 'index', 'text'),
('t_02oexkpyyjr37', 'en', 'info@drtahademir.com', 'index', 'text'),
('t_gzl24x1d6m0ys', 'tr', '0532 171 78 40', 'index', 'text'),
('t_gzl24x1d6m0ys', 'en', '0532 171 78 40', 'index', 'text'),
('t_0c278mwhivs4b', 'tr', 'Dr. Taha Demir', 'index', 'text'),
('t_0c278mwhivs4b', 'en', 'Dr. Taha Demir', 'index', 'text'),
('t_v083go1ugqv99', 'tr', 'Ortopedi ve Travmatoloji Uzmanı', 'index', 'text'),
('t_v083go1ugqv99', 'en', 'Orthopedics and Traumatology Specialist', 'index', 'text'),
('t_1k62mvp1y8hum', 'tr', 'Dr. Taha Demir OrthoCure Klinik', 'index', 'text'),
('t_1k62mvp1y8hum', 'en', 'Dr. Taha Demir OrthoCure Clinic', 'index', 'text'),
('t_1wtq1uwklpl4i', 'tr', '20+ Yıllık Tecrübe | İstanbul Ataköy', 'index', 'text'),
('t_1wtq1uwklpl4i', 'en', '20+ Years of Experience | Istanbul Ataköy', 'index', 'text'),
('t_1hj8798h55zxk', 'tr', 'Spor Yaralanması Hastası', 'index', 'text'),
('t_1hj8798h55zxk', 'en', 'Sports Injury Patient', 'index', 'text'),
('t_18e0guoyp8mva', 'tr', 'Nazlı Sultan', 'index', 'text'),
('t_18e0guoyp8mva', 'en', 'Nazlı Sultan', 'index', 'text'),
('t_0ajow21q5onld', 'tr', 'Dr. Taha''nın gerçekleştirdiği spor yaralanması ameliyatı sayesinde eski hareket kabiliyetime kavuştum. Gerçekten işinin ustası.', 'index', 'text'),
('t_0ajow21q5onld', 'en', 'Thanks to the sports injury surgery performed by Dr. Taha, I regained my former mobility. He is truly a master of his craft.', 'index', 'text'),
('t_0nq01krl98b06', 'tr', 'Artroskopik Cerrahi Hastası', 'index', 'text'),
('t_0nq01krl98b06', 'en', 'Arthroscopic Surgery Patient', 'index', 'text'),
('t_q0g8js1cn2seo', 'tr', 'Şahin Yıldız', 'index', 'text'),
('t_q0g8js1cn2seo', 'en', 'Şahin Yıldız', 'index', 'text'),
('t_012071kkf01ky', 'tr', 'Mükemmel bir artroskopik cerrahi geçirdim. Dr. Taha''nın uzmanlığı ve ilgisi iyileşme sürecimi çok kolaylaştırdı. Çok profesyonel.', 'index', 'text'),
('t_012071kkf01ky', 'en', 'I had an excellent arthroscopic surgery. Dr. Taha''s expertise and attentiveness made my recovery process much easier. Very professional.', 'index', 'text'),
('t_r4ykra1f30c91', 'tr', 'Diz Protezi Hastası', 'index', 'text'),
('t_r4ykra1f30c91', 'en', 'Knee Replacement Patient', 'index', 'text'),
('t_151gp5v5979dy', 'tr', 'Tülay Akbaş', 'index', 'text'),
('t_151gp5v5979dy', 'en', 'Tülay Akbaş', 'index', 'text'),
('t_12qi5le1qpr63b', 'tr', 'Diz protezi tedavim sonrası sonuçlar harika. Dr. Taha çok şefkatli ve son derece yetenekli bir uzman. Teşekkür ederim!', 'index', 'text'),
('t_12qi5le1qpr63b', 'en', 'The results after my knee replacement treatment are amazing. Dr. Taha is a very compassionate and highly skilled specialist. Thank you!', 'index', 'text'),
('t_1ta5uch1mbv8kn', 'tr', 'Kalça Protezi Hastası', 'index', 'text'),
('t_1ta5uch1mbv8kn', 'en', 'Hip Replacement Patient', 'index', 'text'),
('t_0j0ap7ilp938d', 'tr', 'Kemal Aslan', 'index', 'text'),
('t_0j0ap7ilp938d', 'en', 'Kemal Aslan', 'index', 'text'),
('t_0cfnxqjo0yvfx', 'tr', 'Dr. Taha Demir kalça protezi ameliyatımı olağanüstü bir titizlikle gerçekleştirdi. Hareket kabiliyetim tamamen geri döndü. Kesinlikle tavsiye ederim!', 'index', 'text'),
('t_0cfnxqjo0yvfx', 'en', 'Dr. Taha Demir performed my hip replacement surgery with extraordinary care. My mobility has fully returned. I highly recommend him!', 'index', 'text'),
('t_1y8mr8514asqtq', 'tr', 'Hastalarımız Ne Diyor?', 'index', 'text'),
('t_1y8mr8514asqtq', 'en', 'What Our Patients Say', 'index', 'text'),
('t_890dqm1myhqe5', 'tr', 'Hasta Yorumları', 'index', 'text'),
('t_890dqm1myhqe5', 'en', 'Patient Reviews', 'index', 'text'),
('t_n84xbe1rmw4yp', 'tr', 'Randevu Oluştur', 'index', 'text'),
('t_n84xbe1rmw4yp', 'en', 'Book Appointment', 'index', 'text'),
('t_17eo3mv1nl1fj3', 'tr', 'Ataköy Towers, A Blok, Kat 4, No 79,', 'index', 'text'),
('t_17eo3mv1nl1fj3', 'en', 'Ataköy Towers, A Blok, Kat 4, No 79,', 'index', 'text'),
('t_0iqy0ic1y88uw', 'tr', 'Bakırköy/İstanbul', 'index', 'text'),
('t_0iqy0ic1y88uw', 'en', 'Bakırköy/İstanbul', 'index', 'text'),
('t_1j8nv8k1goomab', 'tr', 'Adres:', 'index', 'text'),
('t_1j8nv8k1goomab', 'en', 'Address:', 'index', 'text'),
('t_1blc02211vp03o', 'tr', 'Saat:', 'index', 'text'),
('t_1blc02211vp03o', 'en', 'Hours:', 'index', 'text'),
('t_1eh3fntxe4hgm', 'tr', 'Konsültasyon ve randevu için kliniğimizi ziyaret edin.', 'index', 'text'),
('t_1eh3fntxe4hgm', 'en', 'Visit our clinic for consultation and appointments.', 'index', 'text'),
('t_o1z68c1d53fx7', 'tr', 'Klinik Bilgilerimiz', 'index', 'text'),
('t_o1z68c1d53fx7', 'en', 'Our Clinic Information', 'index', 'text'),
('t_1ujefpq1hz8rru', 'tr', 'ÇALIŞMA SAATLERİ VE KONSÜLTASYON', 'index', 'text'),
('t_1ujefpq1hz8rru', 'en', 'WORKING HOURS AND CONSULTATION', 'index', 'text'),
('t_1l7oypx6rgvlo', 'tr', 'Biruni Üniversitesi', 'index', 'text'),
('t_1l7oypx6rgvlo', 'en', 'Biruni University', 'index', 'text'),
('t_1i3i5mq14ns992', 'tr', 'El Cerrahisi Eğitimi', 'index', 'text'),
('t_1i3i5mq14ns992', 'en', 'Hand Surgery Training', 'index', 'text'),
('t_1l2drlq1abzzpd', 'tr', 'Özel Medicine Hospital', 'index', 'text'),
('t_1l2drlq1abzzpd', 'en', 'Özel Medicine Hospital', 'index', 'text'),
('t_0yt1689y03506', 'tr', 'Kök Hücre, Eksozom ve PRP Uygulamaları Eğitimi', 'index', 'text'),
('t_0yt1689y03506', 'en', 'Stem Cell, Exosome, and PRP Applications Training', 'index', 'text'),
('t_1txl8axz4ho00', 'tr', 'Türk Ortopedi ve Travmatoloji Kongresi', 'index', 'text'),
('t_1txl8axz4ho00', 'en', 'Turkish Orthopedics and Traumatology Congress', 'index', 'text'),
('t_17m08t71hfb1wa', 'tr', 'Spor Yaralanmaları Eğitimi', 'index', 'text'),
('t_17m08t71hfb1wa', 'en', 'Sports Injuries Training', 'index', 'text'),
('t_1faptau1rroum0', 'tr', 'Çocuk Ortopedisi Eğitimi', 'index', 'text'),
('t_1faptau1rroum0', 'en', 'Pediatric Orthopedics Training', 'index', 'text'),
('t_1np1ozl19twtlm', 'tr', 'Atlas Üniversitesi', 'index', 'text'),
('t_1np1ozl19twtlm', 'en', 'Atlas University', 'index', 'text'),
('t_081uthrvj8iyv', 'tr', 'Deformite ve Boy Uzatma Cerrahisi Eğitimi', 'index', 'text'),
('t_081uthrvj8iyv', 'en', 'Deformity and Limb Lengthening Surgery Training', 'index', 'text'),
('t_0fpjo984rdero', 'tr', 'Omurga Cerrahisi Eğitimi', 'index', 'text'),
('t_0fpjo984rdero', 'en', 'Spine Surgery Training', 'index', 'text'),
('t_07acgyvf70c2r', 'tr', 'Diz ve Kalça Protez Cerrahisi Eğitimi', 'index', 'text'),
('t_07acgyvf70c2r', 'en', 'Knee and Hip Replacement Surgery Training', 'index', 'text'),
('t_14te0rs1quqw14', 'tr', 'Uluslararası Ortopedi Kongresi, İstanbul', 'index', 'text'),
('t_14te0rs1quqw14', 'en', 'International Orthopedics Congress, Istanbul', 'index', 'text'),
('t_4439am1x93tq6', 'tr', 'Artroskopik Cerrahi Kursu', 'index', 'text'),
('t_4439am1x93tq6', 'en', 'Arthroscopic Surgery Course', 'index', 'text'),
('t_1d56z9n8djzzy', 'tr', 'İstanbul Üniversitesi Cerrahpaşa Tıp Fakültesi', 'index', 'text'),
('t_1d56z9n8djzzy', 'en', 'Istanbul University Cerrahpaşa Faculty of Medicine', 'index', 'text'),
('t_037ric33ebwj4', 'tr', 'Eklem Protez Cerrahisi Eğitimi', 'index', 'text'),
('t_037ric33ebwj4', 'en', 'Joint Replacement Surgery Training', 'index', 'text'),
('t_1jm6h0e7onl9n', 'tr', 'İleri Eğitimler ve Kurslar', 'index', 'text'),
('t_1jm6h0e7onl9n', 'en', 'Advanced Training and Courses', 'index', 'text'),
('t_mxfj8o1217whr', 'tr', 'Yardımcı Doçent ve Doktor Öğretim Üyesi', 'index', 'text'),
('t_mxfj8o1217whr', 'en', 'Assistant Professor and Faculty Member', 'index', 'text'),
('t_1c8kx0r1h5uqb3', 'tr', 'Biruni ve Atlas Üniversitesi', 'index', 'text'),
('t_1c8kx0r1h5uqb3', 'en', 'Biruni and Atlas University', 'index', 'text'),
('t_10jzx7bt8eeq9', 'tr', '12 yıl hizmet, 2013-2025', 'index', 'text'),
('t_10jzx7bt8eeq9', 'en', '12 years of service, 2013-2025', 'index', 'text'),
('t_0eod5wtkcxv1s', 'tr', 'Nusaybin Devlet Hastanesi, Ortopedi Kliniği', 'index', 'text'),
('t_0eod5wtkcxv1s', 'en', 'Nusaybin State Hospital, Orthopedics Clinic', 'index', 'text'),
('t_1j2rwc7udlqeu', 'tr', 'Zorunlu Hizmet', 'index', 'text'),
('t_1j2rwc7udlqeu', 'en', 'Compulsory Service', 'index', 'text'),
('t_1ob47wn10ni1aq', 'tr', 'Acıbadem Kadıköy Hastanesi, Ortopedi Bölümü', 'index', 'text'),
('t_1ob47wn10ni1aq', 'en', 'Acıbadem Kadıköy Hospital, Orthopedics Department', 'index', 'text'),
('t_lk0z351fm24el', 'tr', 'Acıbadem', 'index', 'text'),
('t_lk0z351fm24el', 'en', 'Acıbadem', 'index', 'text'),
('t_1ohcmij1ygn6t7', 'tr', 'İstanbul Üniversitesi', 'index', 'text'),
('t_1ohcmij1ygn6t7', 'en', 'Istanbul University', 'index', 'text'),
('t_0adae88kxq3pi', 'tr', 'Ortopedi ve Travmatoloji', 'index', 'text'),
('t_0adae88kxq3pi', 'en', 'Orthopedics and Traumatology', 'index', 'text'),
('t_0xl8qh8lw48pb', 'tr', 'Tıp Doktoru', 'index', 'text'),
('t_0xl8qh8lw48pb', 'en', 'Doctor of Medicine', 'index', 'text'),
('t_0tvx8z2hck359', 'tr', 'Mesleki Deneyim ve Görevler', 'index', 'text'),
('t_0tvx8z2hck359', 'en', 'Professional Experience and Positions', 'index', 'text'),
('t_0d5t7r41xdlgh', 'tr', 'Mesleki Deneyim', 'index', 'text'),
('t_0d5t7r41xdlgh', 'en', 'Professional Experience', 'index', 'text'),
('t_0i9p0yliv03f6', 'tr', 'Yardımcı Doçent / Öğretim Üyesi', 'index', 'text'),
('t_0i9p0yliv03f6', 'en', 'Assistant Professor / Faculty Member', 'index', 'text'),
('t_0ufpcig8tiwon', 'tr', 'Akademik Görev', 'index', 'text'),
('t_0ufpcig8tiwon', 'en', 'Academic Position', 'index', 'text'),
('t_blc63v109y2ux', 'tr', 'Nusaybin Devlet Hastanesi, 2011-2013', 'index', 'text'),
('t_blc63v109y2ux', 'en', 'Nusaybin State Hospital, 2011-2013', 'index', 'text'),
('t_ommxsq1nj4cus', 'tr', 'Ortopedi Bölümü, 2011', 'index', 'text'),
('t_ommxsq1nj4cus', 'en', 'Orthopedics Department, 2011', 'index', 'text'),
('t_0ps92fqh9lyy9', 'tr', 'Acıbadem Kadıköy Hastanesi', 'index', 'text'),
('t_0ps92fqh9lyy9', 'en', 'Acıbadem Kadıköy Hospital', 'index', 'text'),
('t_1088bod1e6q5lj', 'tr', 'Görev', 'index', 'text'),
('t_1088bod1e6q5lj', 'en', 'Position', 'index', 'text'),
('t_01jxxdf324gdm', 'tr', 'Cerrahpaşa Tıp Fakültesi, 2011', 'index', 'text'),
('t_01jxxdf324gdm', 'en', 'Cerrahpaşa Faculty of Medicine, 2011', 'index', 'text'),
('t_14eo4da1000qis', 'tr', 'Uzmanlık', 'index', 'text'),
('t_14eo4da1000qis', 'en', 'Specialization', 'index', 'text'),
('t_0s9mq35jggjno', 'tr', 'İstanbul Üniversitesi, 2004', 'index', 'text'),
('t_0s9mq35jggjno', 'en', 'Istanbul University, 2004', 'index', 'text'),
('t_1n3zzdq1jpq917', 'tr', 'İstanbul Tıp Fakültesi', 'index', 'text'),
('t_1n3zzdq1jpq917', 'en', 'Istanbul Faculty of Medicine', 'index', 'text'),
('t_11i4no210iwnk7', 'tr', 'Eğitim, Uzmanlık ve İleri Eğitimler', 'index', 'text'),
('t_11i4no210iwnk7', 'en', 'Education, Specialization, and Advanced Training', 'index', 'text'),
('t_1r2m0cu1qkvamx', 'tr', 'Eğitim ve Uzmanlık', 'index', 'text'),
('t_1r2m0cu1qkvamx', 'en', 'Education and Expertise', 'index', 'text'),
('t_13a3frx15w902l', 'tr', 'Facebook''ta Takip Et', 'index', 'text'),
('t_13a3frx15w902l', 'en', 'Follow on Facebook', 'index', 'text'),
('t_0p2psjfy31z7b', 'tr', 'Eklem kıkırdağı ve yumuşak doku iyileşmesini destekleyen ileri biyolojik tedavilerdir; ağrıyı azaltır ve iyileşmeyi hızlandırır.', 'index', 'text'),
('t_0p2psjfy31z7b', 'en', 'Advanced biological treatments that support joint cartilage and soft tissue healing; reduce pain and accelerate recovery.', 'index', 'text'),
('t_0odlw0vsgwfnw', 'tr', 'Kök Hücre, Eksozom, PRP', 'index', 'text'),
('t_0odlw0vsgwfnw', 'en', 'Stem Cell, Exosome, PRP', 'index', 'text'),
('t_zlsk221r1upql', 'tr', 'Travma sonrası oluşan kırık ve çıkıkların modern tekniklerle tedavisi, kalıcı hareket kısıtlılığını önlemek için hızlıca uygulanır.', 'index', 'text'),
('t_zlsk221r1upql', 'en', 'Post-traumatic fractures and dislocations are treated with modern techniques, applied quickly to prevent permanent mobility limitation.', 'index', 'text'),
('t_169ufr1y2clip', 'tr', 'Kırık ve Çıkık Cerrahisi', 'index', 'text'),
('t_169ufr1y2clip', 'en', 'Fracture and Dislocation Surgery', 'index', 'text'),
('t_1gvltp4w5mx6l', 'tr', 'El ve el bileği yaralanmaları, sinir sıkışmaları ve tendon sorunlarının cerrahi tedavisiyle el fonksiyonları geri kazandırılır.', 'index', 'text'),
('t_1gvltp4w5mx6l', 'en', 'Hand function is restored through surgical treatment of hand and wrist injuries, nerve compressions, and tendon problems.', 'index', 'text'),
('t_1xctp041qqqj7c', 'tr', 'El Cerrahisi', 'index', 'text'),
('t_1xctp041qqqj7c', 'en', 'Hand Surgery', 'index', 'text')
ON CONFLICT (key, lang) DO NOTHING;

INSERT INTO public.site_texts (key, lang, value, page, kind) VALUES
('t_1bcie9tix5hpc', 'tr', 'Çocuklarda gelişimsel kalça displazisi, ayak deformiteleri ve kırıkların tedavisini kapsar. Erken tanı ile uzun vadeli hareket kabiliyeti korunur.', 'index', 'text'),
('t_1bcie9tix5hpc', 'en', 'Covers the treatment of developmental hip dysplasia, foot deformities, and fractures in children. Early diagnosis preserves long-term mobility.', 'index', 'text'),
('t_10sh48fq7g8r4', 'tr', 'Şişlik, ağrı ve kırığa yol açan kemik ve yumuşak doku tümörlerinin cerrahi tedavisidir. Fonksiyon kaybını önlemeye yönelik planlanır ve uygulanır.', 'index', 'text'),
('t_10sh48fq7g8r4', 'en', 'Surgical treatment of bone and soft tissue tumors causing swelling, pain, and fractures. It is planned and performed to prevent loss of function.', 'index', 'text'),
('t_1y67bmyz6u0f8', 'tr', 'Kemik ve Yumuşak Doku Tümör Cerrahisi', 'index', 'text'),
('t_1y67bmyz6u0f8', 'en', 'Bone and Soft Tissue Tumor Surgery', 'index', 'text'),
('t_1jwf85i1sugyfw', 'tr', 'Hareket kabiliyetini geri kazandırmaya ve eklem sağlığını korumaya odaklı ileri prosedürler.', 'index', 'text'),
('t_1jwf85i1sugyfw', 'en', 'Advanced procedures focused on restoring mobility and preserving joint health.', 'index', 'text'),
('t_07dhi9ztpkkwh', 'tr', 'Eklem ve Omurga Rahatsızlıkları için Cerrahi Çözümler', 'index', 'text'),
('t_07dhi9ztpkkwh', 'en', 'Surgical Solutions for Joint and Spine Disorders', 'index', 'text'),
('t_0fjd4eggna0ak', 'tr', 'İleri Ortopedik Bakım', 'index', 'text'),
('t_0fjd4eggna0ak', 'en', 'Advanced Orthopedic Care', 'index', 'text'),
('t_0wfv39jcyc3si', 'tr', 'Boy Uzatma', 'index', 'text'),
('t_0wfv39jcyc3si', 'en', 'Height Lengthening', 'index', 'text'),
('t_08axq0xl1t32g', 'tr', '04', 'index', 'text'),
('t_08axq0xl1t32g', 'en', '04', 'index', 'text'),
('t_8kxbpw1fmxkzr', 'tr', '03', 'index', 'text'),
('t_8kxbpw1fmxkzr', 'en', '03', 'index', 'text'),
('t_08uwxevhriqcy', 'tr', '02', 'index', 'text'),
('t_08uwxevhriqcy', 'en', '02', 'index', 'text'),
('t_0r46k4giqb851', 'tr', 'Ayak ve Ayak Bileği', 'index', 'text'),
('t_0r46k4giqb851', 'en', 'Foot and Ankle', 'index', 'text'),
('t_94wj3u1ccn8a9', 'tr', '01', 'index', 'text'),
('t_94wj3u1ccn8a9', 'en', '01', 'index', 'text'),
('t_nmax391ilnhma', 'tr', 'Tendon kopmaları, eklem aşınmaları ve hareket kısıtlılığı tedavi edilmezse ciddi fonksiyon kaybına yol açabilir. Erken teşhis ve cerrahi müdahale eklem fonksiyonlarını etkili biçimde geri kazandırır.', 'index', 'text'),
('t_nmax391ilnhma', 'en', 'If tendon tears, joint wear, and limited mobility are not treated, they can lead to severe loss of function. Early diagnosis and surgical intervention effectively restore joint function.', 'index', 'text'),
('t_08qq0qtv0u42u', 'tr', 'Eklem içi problemlerin teşhis ve tedavisinde kullanılan minimal invaziv yöntem; menisküs, kıkırdak ve bağ yaralanmalarını onararak ilerlemeyi yavaşlatır ve hareket kabiliyetini korur.', 'index', 'text'),
('t_08qq0qtv0u42u', 'en', 'A minimally invasive method used to diagnose and treat problems inside the joint; repairs meniscus, cartilage, and ligament injuries, slowing progression and preserving mobility.', 'index', 'text'),
('t_0fo2mw3h1jzc1', 'tr', 'Artroskopik Cerrahi (Kapalı)', 'index', 'text'),
('t_0fo2mw3h1jzc1', 'en', 'Arthroscopic (Keyhole) Surgery', 'index', 'text'),
('t_1oycl7c1yflsiz', 'tr', 'Tedavi planı hasarın tipine, konumuna ve hastanın genel sağlık durumuna göre kişiye özel olarak belirlenir.', 'index', 'text'),
('t_1oycl7c1yflsiz', 'en', 'The treatment plan is personalized based on the type and location of the damage and the patient''s overall health condition.', 'index', 'text'),
('t_1nesg2krrdj1i', 'tr', 'Hasarlı eklemin yapay eklemle değiştirilerek ağrının azaltıldığı ve hareket kabiliyetinin geri kazandırıldığı cerrahi tedavidir. Zamanında müdahale edilmediğinde kalıcı hareket kısıtlılığına yol açabilir.', 'index', 'text'),
('t_1nesg2krrdj1i', 'en', 'A surgical treatment in which the damaged joint is replaced with an artificial joint to reduce pain and restore mobility. If not treated in time, it can lead to permanent mobility limitation.', 'index', 'text'),
('t_apnohm18ernnp', 'tr', 'Ortopedik ameliyat bilgisini paylaş', 'index', 'attr'),
('t_apnohm18ernnp', 'en', 'Ortopedik ameliyat bilgisini paylaş', 'index', 'attr'),
('t_0p894vkwldbav', 'tr', 'Bilgiyi Paylaş', 'index', 'text'),
('t_0p894vkwldbav', 'en', 'Share Information', 'index', 'text'),
('t_0dk2kvukhay78', 'tr', 'İleri Ortopedik Bakım ve Cerrahi Çözümler', 'index', 'text'),
('t_0dk2kvukhay78', 'en', 'Advanced Orthopedic Care and Surgical Solutions', 'index', 'text'),
('t_1ntyh5e1tdc8ei', 'tr', 'Ortopedik tedavi videosunu oynat', 'index', 'attr'),
('t_1ntyh5e1tdc8ei', 'en', 'Play orthopedic treatment video', 'index', 'attr'),
('t_1pdt62ilakch0', 'tr', 'İleri ortopedik bakım ve cerrahi çözümler', 'index', 'attr'),
('t_1pdt62ilakch0', 'en', 'Advanced orthopedic care and surgical solutions', 'index', 'attr'),
('t_1u0ex2l1g3alb1', 'tr', 'Eklem protezi, artroskopik cerrahi, omurga ve travma tedavilerinde kişiye özel kapsamlı bakım', 'index', 'text'),
('t_1u0ex2l1g3alb1', 'en', 'Personalized, comprehensive care in joint replacement, arthroscopic surgery, spine, and trauma treatments', 'index', 'text'),
('t_1jlbeje6z7uxb', 'tr', 'Hareketinizi Geri Kazandıran Ortopedik Çözümler', 'index', 'text'),
('t_1jlbeje6z7uxb', 'en', 'Orthopedic Solutions That Restore Your Mobility', 'index', 'text'),
('t_1vq8zel10ov08f', 'tr', 'Ortopedik Tedavi Alanları', 'index', 'text'),
('t_1vq8zel10ov08f', 'en', 'Orthopedic Treatment Areas', 'index', 'text'),
('t_1egwwcd63p4fp', 'tr', 'Devamını Oku', 'index', 'text'),
('t_1egwwcd63p4fp', 'en', 'Read More', 'index', 'text'),
('t_1fiworl1vtk0c', 'tr', 'Eklem kıkırdağı ve yumuşak doku iyileşmesini destekleyen ileri biyolojik tedaviler.', 'index', 'text'),
('t_1fiworl1vtk0c', 'en', 'Advanced biological treatments that support joint cartilage and soft tissue healing.', 'index', 'text'),
('t_0f0y5hb42wh5e', 'tr', 'Bağ, menisküs ve tendon yaralanmalarında sporcuya özel cerrahi ve rehabilitasyon planı.', 'index', 'text'),
('t_0f0y5hb42wh5e', 'en', 'A surgical and rehabilitation plan tailored to athletes for ligament, meniscus, and tendon injuries.', 'index', 'text'),
('t_18pd07xooyevo', 'tr', 'Spor Yaralanmaları', 'index', 'text'),
('t_18pd07xooyevo', 'en', 'Sports Injuries', 'index', 'text'),
('t_0udtmefi7qst2', 'tr', 'Travma sonrası kırık ve çıkıkların modern tekniklerle tedavisi.', 'index', 'text'),
('t_0udtmefi7qst2', 'en', 'Treatment of post-traumatic fractures and dislocations using modern techniques.', 'index', 'text'),
('t_1q08d5swxzlys', 'tr', 'El ve el bileği yaralanmaları, sinir sıkışmaları ve tendon sorunlarının cerrahi tedavisi.', 'index', 'text'),
('t_1q08d5swxzlys', 'en', 'Surgical treatment of hand and wrist injuries, nerve compressions, and tendon problems.', 'index', 'text'),
('t_0vegf8jyfp9tq', 'tr', 'Çocuklarda gelişimsel kalça displazisi, ayak deformiteleri ve kırıkların tedavisi.', 'index', 'text'),
('t_0vegf8jyfp9tq', 'en', 'Treatment of developmental hip dysplasia, foot deformities, and fractures in children.', 'index', 'text'),
('t_1sf56764o7voc', 'tr', 'Şişlik, ağrı ve kırığa yol açan tümörlerin cerrahi tedavisi; fonksiyon kaybını önler.', 'index', 'text'),
('t_1sf56764o7voc', 'en', 'Surgical treatment of tumors causing swelling, pain, and fractures; prevents loss of function.', 'index', 'text'),
('t_19ntjxenam3nw', 'tr', 'Planlı kemik uzatma teknikleriyle boy uzatma ve oran düzeltme cerrahisi.', 'index', 'text'),
('t_19ntjxenam3nw', 'en', 'Height lengthening and body proportion correction surgery using planned bone lengthening techniques.', 'index', 'text'),
('t_1egxy8b1rxpeh0', 'tr', 'Kozmetik Boy Uzatma', 'index', 'text'),
('t_1egxy8b1rxpeh0', 'en', 'Cosmetic Height Lengthening', 'index', 'text'),
('t_1bzb2n12hrihl', 'tr', 'Doğuştan veya sonradan gelişen kemik ve eklem bozukluklarını düzeltir, hareket kabiliyetini ve estetik görünümü iyileştirir.', 'index', 'text'),
('t_1bzb2n12hrihl', 'en', 'Corrects congenital or acquired bone and joint disorders, improving mobility and appearance.', 'index', 'text'),
('t_17wnxku1itsruw', 'tr', 'Omurga kaynaklı ağrı, sıkışma ve şekil bozukluklarının cerrahi tedavisi.', 'index', 'text'),
('t_17wnxku1itsruw', 'en', 'Surgical treatment of spine-related pain, nerve compression, and deformities.', 'index', 'text'),
('t_0yd9r6lkkjxe6', 'tr', 'Travma, deformite, kireçlenme ve yaralanmalara bağlı ağrı ve hareket kısıtlılığını giderir.', 'index', 'text'),
('t_0yd9r6lkkjxe6', 'en', 'Relieves pain and limited mobility caused by trauma, deformity, arthritis, and injuries.', 'index', 'text'),
('t_0hw1wqw4xowxe', 'tr', 'Ayak ve Ayak Bileği Cerrahisi', 'index', 'text'),
('t_0hw1wqw4xowxe', 'en', 'Foot and Ankle Surgery', 'index', 'text'),
('t_e0vudb1e0ook0', 'tr', 'Tendon kopmaları, eklem aşınmaları ve hareket kısıtlılığının tedavisinde eklem fonksiyonlarını geri kazandırır.', 'index', 'text'),
('t_e0vudb1e0ook0', 'en', 'Restores joint function in the treatment of tendon tears, joint wear, and limited mobility.', 'index', 'text'),
('t_eg2iau1bw0z3o', 'tr', 'Eklem içi problemlerin teşhis ve tedavisinde kullanılan minimal invaziv yöntem; menisküs, kıkırdak ve bağ yaralanmalarını onarır.', 'index', 'text'),
('t_eg2iau1bw0z3o', 'en', 'A minimally invasive method used to diagnose and treat problems inside the joint; repairs meniscus, cartilage, and ligament injuries.', 'index', 'text'),
('t_1493qqx1ya0xo5', 'tr', 'İleri kireçlenme, eklem aşınması veya hareket kısıtlılığında uygulanır; ağrıyı azaltır, yaşam kalitesini artırır.', 'index', 'text'),
('t_1493qqx1ya0xo5', 'en', 'Applied in cases of advanced arthritis, joint wear, or limited mobility; reduces pain and improves quality of life.', 'index', 'text'),
('t_007krkvh4isrn', 'tr', 'Hasarlı eklemin yapay eklemle değiştirilerek ağrının azaltıldığı ve hareket kabiliyetinin geri kazandırıldığı cerrahi tedavi.', 'index', 'text'),
('t_007krkvh4isrn', 'en', 'A surgical treatment in which the damaged joint is replaced with an artificial joint to reduce pain and restore mobility.', 'index', 'text'),
('t_1daxrfn2nttxj', 'tr', 'Ağrılarınızı azaltmak ve hareket kabiliyetinizi geri kazandırmak için uzman ve şefkatli bakımla tasarlanmış tedavileri keşfedin.', 'index', 'text'),
('t_1daxrfn2nttxj', 'en', 'Discover treatments designed with expert and compassionate care to reduce your pain and restore your mobility.', 'index', 'text'),
('t_t98kza1oqg6e6', 'tr', 'Öne Çıkan', 'index', 'text'),
('t_t98kza1oqg6e6', 'en', 'Featured', 'index', 'text'),
('t_1ka08l91q8uq9k', 'tr', 'Ortopedi ve Travmatoloji Hizmetleri', 'index', 'text'),
('t_1ka08l91q8uq9k', 'en', 'Orthopedics and Traumatology Services', 'index', 'text'),
('t_05a9y2oyw3l61', 'tr', 'Ortopedi ve Travmatoloji Uzmanı | 10.000+ Ameliyat', 'index', 'text'),
('t_05a9y2oyw3l61', 'en', 'Orthopedics and Traumatology Specialist | 10,000+ Surgeries', 'index', 'text'),
('t_1bfnaqd1qu9rnu', 'tr', '20+ Yıllık Tecrübe', 'index', 'text'),
('t_1bfnaqd1qu9rnu', 'en', '20+ Years of Experience', 'index', 'text'),
('t_op4szf1w0qdxs', 'tr', 'Randevu ve konsültasyon için arayın', 'index', 'text'),
('t_op4szf1w0qdxs', 'en', 'Call for appointment and consultation', 'index', 'text'),
('t_184e9c51uoya5r', 'tr', 'Dr. Taha Demir - Ortopedi ve Travmatoloji Uzmanı ofisinde', 'index', 'attr'),
('t_184e9c51uoya5r', 'en', 'Dr. Taha Demir - Ortopedi ve Travmatoloji Uzmanı ofisinde', 'index', 'attr'),
('t_1fsh85z5fvfjz', 'tr', 'Cumartesi | 10:00 - 14:00', 'index', 'text'),
('t_1fsh85z5fvfjz', 'en', 'Saturday | 10:00 - 14:00', 'index', 'text'),
('t_1a3c8sowx3of2', 'tr', 'Pazartesi - Cuma | 10:00 - 18:00', 'index', 'text'),
('t_1a3c8sowx3of2', 'en', 'Monday - Friday | 10:00 - 18:00', 'index', 'text'),
('t_0am1xg1n1rl7s', 'tr', 'Yaklaşık 20 yıllık mesleki tecrübesiyle Ortopedi ve Travmatoloji alanında', 'index', 'text'),
('t_0am1xg1n1rl7s', 'en', 'With approximately 20 years of professional experience in Orthopedics and Traumatology,', 'index', 'text'),
('t_1x0jw226m7gej', 'tr', 'gerçekleştiren Dr. Taha Demir, ileri düzeyde İngilizce bilmektedir. Halen İstanbul Ataköy’deki özel kliniğinde hasta kabul etmeye devam etmektedir.', 'index', 'text'),
('t_1x0jw226m7gej', 'en', 'Dr. Taha Demir has performed and has an advanced level of English. He continues to see patients at his private clinic in Ataköy, Istanbul.', 'index', 'text'),
('t_183qanq1skxjyw', 'tr', '10.000’in üzerinde başarılı ameliyat', 'index', 'text'),
('t_183qanq1skxjyw', 'en', 'over 10,000 successful surgeries', 'index', 'text'),
('t_1iypjgl1hs2cex', 'tr', '2013 yılında', 'index', 'text'),
('t_1iypjgl1hs2cex', 'en', 'In 2013', 'index', 'text'),
('t_1b8j83q39nhfl', 'tr', 'çalışmaya başlayan Dr. Taha Demir, burada 12 yıl boyunca hizmet vermiştir. Bu süreçte, Yardımcı Doçent ve Doktor Öğretim Üyesi unvanlarıyla Biruni Üniversitesi ve Atlas Üniversitesi’nde akademik çalışmalar yürütmüştür.', 'index', 'text'),
('t_1b8j83q39nhfl', 'en', 'Dr. Taha Demir began working there and served for 12 years. During this time, he carried out academic work at Biruni University and Atlas University as an Assistant Professor and Faculty Member.', 'index', 'text'),
('t_29xzsy1nw10mg', 'tr', 'Özel Medicine Hospital’de', 'index', 'text'),
('t_29xzsy1nw10mg', 'en', 'at Özel Medicine Hospital', 'index', 'text'),
('t_0yf7hkr1aiad7', 'tr', 'Dr. Taha Demir, 10 Ekim 1980 doğumludur. 2004 yılında İstanbul Üniversitesi İstanbul Tıp Fakültesi’nden mezun olarak Tıp Doktoru unvanını almıştır. Ortopedi ve Travmatoloji ihtisasını 2011 yılında İstanbul Üniversitesi Cerrahpaşa Tıp Fakültesi’nde tamamlayarak Ortopedi Uzmanı olmuştur. Aynı yıl Acıbadem Kadıköy Hastanesi Ortopedi bölümünde görev yapmaya başlamış, ardından 2011-2013 yılları arasında Nusaybin Devlet Hastanesi Ortopedi Kliniği’nde zorunlu hizmetini tamamlamıştır.', 'index', 'text'),
('t_0yf7hkr1aiad7', 'en', 'Dr. Taha Demir was born on October 10, 1980. He graduated from Istanbul University Istanbul Faculty of Medicine in 2004, earning his Doctor of Medicine degree. He completed his specialization in Orthopedics and Traumatology at Istanbul University Cerrahpaşa Faculty of Medicine in 2011, becoming an Orthopedic Specialist. That same year, he began working in the Orthopedics Department of Acıbadem Kadıköy Hospital, and between 2011 and 2013 completed his compulsory service at the Orthopedics Clinic of Nusaybin State Hospital.', 'index', 'text'),
('t_1c4axuj1h6cpxq', 'tr', 'Dr. Taha Demir Kimdir?', 'index', 'text'),
('t_1c4axuj1h6cpxq', 'en', 'Who is Dr. Taha Demir?', 'index', 'text'),
('t_0dgbiiiei1lon', 'tr', 'Hakkımızda', 'index', 'text'),
('t_0dgbiiiei1lon', 'en', 'About Us', 'index', 'text'),
('t_0icr3oe7opdgr', 'tr', 'Dr. Taha Demir - İstanbul Ataköy Klinik', 'index', 'attr'),
('t_0icr3oe7opdgr', 'en', 'Dr. Taha Demir - İstanbul Ataköy Klinik', 'index', 'attr'),
('t_1ozubm51liotls', 'tr', 'Hafta Sonu Kliniği', 'index', 'text'),
('t_1ozubm51liotls', 'en', 'Weekend Clinic', 'index', 'text'),
('t_1ayabpp19cxghj', 'tr', 'İstanbul (Ataköy)', 'index', 'text'),
('t_1ayabpp19cxghj', 'en', 'İstanbul (Ataköy)', 'index', 'text'),
('t_1dt64bggnv1yu', 'tr', 'Klinik Bilgileri', 'index', 'text'),
('t_1dt64bggnv1yu', 'en', 'Clinic Information', 'index', 'text'),
('t_1pjkqbs11dlfi5', 'tr', 'E-posta', 'index', 'text'),
('t_1pjkqbs11dlfi5', 'en', 'Email', 'index', 'text'),
('t_0f8ajvkg1rfc4', 'tr', 'Hemen Ara', 'index', 'text'),
('t_0f8ajvkg1rfc4', 'en', 'Call Now', 'index', 'text'),
('t_1ub5vul1p5y2i6', 'tr', '0532 690 54 24', 'index', 'text'),
('t_1ub5vul1p5y2i6', 'en', '0532 690 54 24', 'index', 'text'),
('t_1d5zzif1qyvi73', 'tr', 'WhatsApp', 'index', 'text'),
('t_1d5zzif1qyvi73', 'en', 'WhatsApp', 'index', 'text'),
('t_0w5nn4panxjol', 'tr', 'Eklem protez cerrahisi, artroskopik cerrahi, spor yaralanmaları ve kapsamlı ortopedik tedaviler için Dr. Taha Demir ile iletişime geçin.', 'index', 'text'),
('t_0w5nn4panxjol', 'en', 'Contact Dr. Taha Demir for joint replacement surgery, arthroscopic surgery, sports injuries, and comprehensive orthopedic treatments.', 'index', 'text'),
('t_1ibrkzupo7ang', 'tr', 'Dr. Taha Demir''e Ulaşın —', 'index', 'text'),
('t_1ibrkzupo7ang', 'en', 'Reach Dr. Taha Demir —', 'index', 'text'),
('t_1a6duyg35yd07', 'tr', 'Keşfetmek için kaydırın', 'index', 'text'),
('t_1a6duyg35yd07', 'en', 'Scroll to explore', 'index', 'text'),
('t_06e0lm3c9s4u6', 'tr', 'Professional highlights', 'index', 'attr'),
('t_06e0lm3c9s4u6', 'en', 'Professional highlights', 'index', 'attr'),
('t_10mokly1vu4bk0', 'tr', 'İstanbul', 'index', 'text'),
('t_10mokly1vu4bk0', 'en', 'İstanbul', 'index', 'text'),
('t_0vyzt9dmzngw2', 'tr', 'Ataköy', 'index', 'text'),
('t_0vyzt9dmzngw2', 'en', 'Ataköy', 'index', 'text'),
('t_1ie9w1um826lm', 'tr', 'Başarılı ameliyat', 'index', 'text'),
('t_1ie9w1um826lm', 'en', 'Successful surgeries', 'index', 'text'),
('t_1cmckqr1v55aoi', 'tr', '10.000+', 'index', 'text'),
('t_1cmckqr1v55aoi', 'en', '10.000+', 'index', 'text'),
('t_u0f9bg1rk6e9l', 'tr', 'Yıllık mesleki tecrübe', 'index', 'text'),
('t_u0f9bg1rk6e9l', 'en', 'Years of professional experience', 'index', 'text'),
('t_1jqrsjgf8jigd', 'tr', '20+', 'index', 'text'),
('t_1jqrsjgf8jigd', 'en', '20+', 'index', 'text'),
('t_mshupg10lr3n9', 'tr', 'Güvenilir uzmanlık', 'index', 'text'),
('t_mshupg10lr3n9', 'en', 'Trusted expertise', 'index', 'text'),
('t_r6gi5j1k2b2ae', 'tr', 'Dr. Taha Demir, Ortopedi ve Travmatoloji Uzmanı', 'index', 'attr'),
('t_r6gi5j1k2b2ae', 'en', 'Dr. Taha Demir, Ortopedi ve Travmatoloji Uzmanı', 'index', 'attr'),
('t_1ndh7bm13q0ahm', 'tr', 'Dr. Taha Demir ile randevu oluşturun', 'index', 'attr'),
('t_1ndh7bm13q0ahm', 'en', 'Dr. Taha Demir ile randevu oluşturun', 'index', 'attr'),
('t_15ynnjpth19bf', 'tr', '→', 'index', 'text'),
('t_15ynnjpth19bf', 'en', '→', 'index', 'text'),
('t_11zh8xg1fe4smy', 'tr', 'Ağrılarınız kaderiniz olmasın. Doğru tanı, kişiye özel tedavi planı ve modern cerrahi yaklaşımlarla yeniden özgürce hareket edin.', 'index', 'text'),
('t_11zh8xg1fe4smy', 'en', 'Don''t let pain be your fate. Move freely again with accurate diagnosis, a personalized treatment plan, and modern surgical approaches.', 'index', 'text'),
('t_dqxcyk15k7o0s', 'tr', '20 Yıllık Tecrübe', 'index', 'text'),
('t_dqxcyk15k7o0s', 'en', '20 Years of Experience', 'index', 'text'),
('t_0vf4e6ppk2qap', 'tr', 'Dr. Taha', 'index', 'text'),
('t_0vf4e6ppk2qap', 'en', 'Dr. Taha', 'index', 'text'),
('t_18083d6mnlxcq', 'tr', 'Demir', 'index', 'text'),
('t_18083d6mnlxcq', 'en', 'Demir', 'index', 'text'),
('t_0s9nydsupxrig', 'tr', 'ORTHOCURE', 'index', 'text'),
('t_0s9nydsupxrig', 'en', 'ORTHOCURE', 'index', 'text'),
('t_12elh4gdbde8s', 'tr', 'Language selector', 'index', 'attr'),
('t_12elh4gdbde8s', 'en', 'Language selector', 'index', 'attr'),
('t_7nql6j1318l76', 'tr', 'English', 'index', 'text'),
('t_7nql6j1318l76', 'en', 'English', 'index', 'text'),
('t_1k7opku1t8kajl', 'tr', 'Türkçe', 'index', 'text'),
('t_1k7opku1t8kajl', 'en', 'Türkçe', 'index', 'text'),
('t_1kfuap9tyi3df', 'tr', 'Tedavi Bilgileri', 'index', 'text'),
('t_1kfuap9tyi3df', 'en', 'Treatment Information', 'index', 'text'),
('t_18kie9q19r4cer', 'tr', 'Ameliyat Görselleri', 'index', 'text'),
('t_18kie9q19r4cer', 'en', 'Surgery Images', 'index', 'text'),
('t_1g82a1snupgi8', 'tr', 'Dr. Taha Demir - Ortopedi ve Travmatoloji Uzmanı', 'index', 'attr'),
('t_1g82a1snupgi8', 'en', 'Dr. Taha Demir - Orthopedics and Traumatology Specialist', 'index', 'attr'),
('t_06kndirmnto6a', 'tr', 'Loading...', 'index', 'text'),
('t_06kndirmnto6a', 'en', 'Loading...', 'index', 'text'),
('t_bo9o271tku3ir', 'tr', 'Dr. Taha Demir - Ortopedi ve Travmatoloji Uzmanı, 20 yıllık tecrübe. Eklem protez cerrahisi, artroskopik cerrahi ve İstanbul Ataköy''de kapsamlı ortopedik bakım.', 'index', 'description'),
('t_bo9o271tku3ir', 'en', 'Dr. Taha Demir - Ortopedi ve Travmatoloji Uzmanı, 20 yıllık tecrübe. Eklem protez cerrahisi, artroskopik cerrahi ve İstanbul Ataköy''de kapsamlı ortopedik bakım.', 'index', 'description'),
('t_1vmzqdi606cds', 'tr', 'Dr. Taha Demir, Ortopedi ve Travmatoloji Uzmanı, Eklem Protez Cerrahisi, Artroskopik Cerrahi, Diz ve Kalça Cerrahisi, Omurga Cerrahisi, İstanbul, Ataköy', 'index', 'keywords'),
('t_1vmzqdi606cds', 'en', 'Dr. Taha Demir, Ortopedi ve Travmatoloji Uzmanı, Eklem Protez Cerrahisi, Artroskopik Cerrahi, Diz ve Kalça Cerrahisi, Omurga Cerrahisi, İstanbul, Ataköy', 'index', 'keywords'),
('t_w8u4oz18xebos', 'tr', 'Dr. Taha Demir | Anasayfa | Ortopedi ve Travmatoloji Uzmanı', 'index', 'title'),
('t_w8u4oz18xebos', 'en', 'Dr. Taha Demir | Home | Orthopedics and Traumatology Specialist', 'index', 'title'),
('t_1bqird01cc5lby', 'tr', '©', 'about', 'text'),
('t_1bqird01cc5lby', 'en', '©', 'about', 'text'),
('t_02mzc37cwtrge', 'tr', ', Tüm Hakları Saklıdır.', 'about', 'text'),
('t_02mzc37cwtrge', 'en', ', All Rights Reserved.', 'about', 'text')
ON CONFLICT (key, lang) DO NOTHING;

INSERT INTO public.site_texts (key, lang, value, page, kind) VALUES
('t_1gabkir1a6e5h', 'tr', 'Pazar', 'about', 'text'),
('t_1gabkir1a6e5h', 'en', 'Sunday', 'about', 'text'),
('t_16xmknh1bdfdvk', 'tr', 'Kapalı', 'about', 'text'),
('t_16xmknh1bdfdvk', 'en', 'Closed', 'about', 'text'),
('t_0qbta9ob920xi', 'tr', 'Ataköy Towers, A Blok, Kat 4, No 79, PK:34158, Bakırköy/İstanbul', 'about', 'text'),
('t_0qbta9ob920xi', 'en', 'Ataköy Towers, A Blok, Kat 4, No 79, PK:34158, Bakırköy/İstanbul', 'about', 'text'),
('t_03gmzbeunydca', 'tr', 'Hızlı Bağlantılar', 'about', 'text'),
('t_03gmzbeunydca', 'en', 'Quick Links', 'about', 'text'),
('t_1axe6b51pexhco', 'tr', 'Ataköy Towers, A Blok, Kat 4, No 79', 'about', 'text'),
('t_1axe6b51pexhco', 'en', 'Ataköy Towers, A Blok, Kat 4, No 79', 'about', 'text'),
('t_0kyyvqqc9jlc9', 'tr', 'Bakırköy / İstanbul', 'about', 'text'),
('t_0kyyvqqc9jlc9', 'en', 'Bakırköy / İstanbul', 'about', 'text'),
('t_0gnv9lrst0um5', 'tr', '0532 171 78 40 | WhatsApp Mevcut', 'about', 'text'),
('t_0gnv9lrst0um5', 'en', '0532 171 78 40 | WhatsApp Available', 'about', 'text'),
('t_0cqcru62durjo', 'tr', 'Pazartesi-Cuma 10:00 – 18:00 | Cumartesi 10:00 – 14:00 | Pazar Kapalı', 'about', 'text'),
('t_0cqcru62durjo', 'en', 'Monday-Friday 10:00 – 18:00 | Saturday 10:00 – 14:00 | Sunday Closed', 'about', 'text'),
('t_1b5s29ch12qum', 'tr', 'Çalışma Saatleri', 'about', 'text'),
('t_1b5s29ch12qum', 'en', 'Working Hours', 'about', 'text'),
('t_00ym1u83gmttu', 'tr', 'Eklem Protez, Diz ve Kalça Cerrahisi, El Cerrahisi, Kırık ve Çıkık Cerrahisi, Çocuk Ortopedisi', 'about', 'text'),
('t_00ym1u83gmttu', 'en', 'Joint Replacement, Knee and Hip Surgery, Hand Surgery, Fracture and Dislocation Surgery, Pediatric Orthopedics', 'about', 'text'),
('t_1e1y4fn1jbztab', 'tr', '20 Yıllık Tecrübe, 10.000+ Başarılı Ameliyat, İleri Düzeyde İngilizce', 'about', 'text'),
('t_1e1y4fn1jbztab', 'en', '20 Years of Experience, 10,000+ Successful Surgeries, Advanced English', 'about', 'text'),
('t_0xjx7t4fbaga9', 'tr', 'Deneyim', 'about', 'text'),
('t_0xjx7t4fbaga9', 'en', 'Experience', 'about', 'text'),
('t_v0mc3x1uph2jt', 'tr', 'Yardımcı Doçent ve Doktor Öğretim Üyesi (Biruni Üniversitesi, Atlas Üniversitesi)', 'about', 'text'),
('t_v0mc3x1uph2jt', 'en', 'Assistant Professor and Faculty Member (Biruni University, Atlas University)', 'about', 'text'),
('t_0bs1pqp1v06n7', 'tr', 'Akademik Unvanlar', 'about', 'text'),
('t_0bs1pqp1v06n7', 'en', 'Academic Titles', 'about', 'text'),
('t_wryns61szstor', 'tr', 'Acıbadem Kadıköy Hastanesi | Nusaybin Devlet Hastanesi | Özel Medicine Hospital', 'about', 'text'),
('t_wryns61szstor', 'en', 'Acıbadem Kadıköy Hospital | Nusaybin State Hospital | Özel Medicine Hospital', 'about', 'text'),
('t_119qd0q6x8y98', 'tr', 'Görev Geçmişi', 'about', 'text'),
('t_119qd0q6x8y98', 'en', 'Work History', 'about', 'text'),
('t_0o3ofgio6uc5v', 'tr', 'Eklem Protez Cerrahisi, Artroskopik Cerrahi, Omurga Cerrahisi, Deformite Cerrahisi, Spor Yaralanmaları, Kök Hücre ve PRP Tedavileri', 'about', 'text'),
('t_0o3ofgio6uc5v', 'en', 'Joint Replacement Surgery, Arthroscopic Surgery, Spine Surgery, Deformity Surgery, Sports Injuries, Stem Cell and PRP Treatments', 'about', 'text'),
('t_1hac1f89g4jbp', 'tr', 'İleri Uzmanlık Alanları', 'about', 'text'),
('t_1hac1f89g4jbp', 'en', 'Advanced Areas of Expertise', 'about', 'text'),
('t_0837fnz54n2h0', 'tr', 'Tıp Doktoru (İstanbul Üniversitesi), Ortopedi ve Travmatoloji Uzmanı (Cerrahpaşa Tıp Fakültesi)', 'about', 'text'),
('t_0837fnz54n2h0', 'en', 'Doctor of Medicine (Istanbul University), Orthopedics and Traumatology Specialist (Cerrahpaşa Faculty of Medicine)', 'about', 'text'),
('t_002odrqw4jrwk', 'tr', 'Ortopedi ve Travmatoloji Uzmanı | Dr. Taha Demir OrthoCure Klinik', 'about', 'text'),
('t_002odrqw4jrwk', 'en', 'Orthopedics and Traumatology Specialist | Dr. Taha Demir OrthoCure Clinic', 'about', 'text'),
('t_1gcjdi35o15vc', 'tr', 'Yardımcı Doçent ve Doktor Öğretim Üyesi unvanlarıyla akademik çalışmalar yürütüldü.', 'about', 'text'),
('t_1gcjdi35o15vc', 'en', 'Carried out academic work as an Assistant Professor and Faculty Member.', 'about', 'text'),
('t_5rkh661jnxe46', 'tr', 'Biruni Üniversitesi ve Atlas Üniversitesi', 'about', 'text'),
('t_5rkh661jnxe46', 'en', 'Biruni University and Atlas University', 'about', 'text'),
('t_0236x276h2ceq', 'tr', 'Akademik Çalışmalar', 'about', 'text'),
('t_0236x276h2ceq', 'en', 'Academic Work', 'about', 'text'),
('t_1rlti38b8vitc', 'tr', 'Eklem protez ve artroskopik cerrahi başta olmak üzere kapsamlı ortopedik cerrahi hizmeti verildi.', 'about', 'text'),
('t_1rlti38b8vitc', 'en', 'Provided comprehensive orthopedic surgical care, primarily in joint replacement and arthroscopic surgery.', 'about', 'text'),
('t_16si8rjhae6if', 'tr', '2013 – 2025 (12 yıl)', 'about', 'text'),
('t_16si8rjhae6if', 'en', '2013 – 2025 (12 years)', 'about', 'text'),
('t_1wuxttf9gau6k', 'tr', 'Zorunlu hizmet, ortopedi kliniğinde tamamlandı.', 'about', 'text'),
('t_1wuxttf9gau6k', 'en', 'Compulsory service completed at the orthopedics clinic.', 'about', 'text'),
('t_1csm0rimi78pr', 'tr', '2011 – 2013', 'about', 'text'),
('t_1csm0rimi78pr', 'en', '2011 – 2013', 'about', 'text'),
('t_1c6r86t7w8bz2', 'tr', 'Nusaybin Devlet Hastanesi Ortopedi Kliniği', 'about', 'text'),
('t_1c6r86t7w8bz2', 'en', 'Nusaybin State Hospital Orthopedics Clinic', 'about', 'text'),
('t_96fmhg17xqyev', 'tr', 'Ortopedi bölümünde göreve başlandı.', 'about', 'text'),
('t_96fmhg17xqyev', 'en', 'Began working in the Orthopedics Department.', 'about', 'text'),
('t_1kxf28xep6ptt', 'tr', '2011', 'about', 'text'),
('t_1kxf28xep6ptt', 'en', '2011', 'about', 'text'),
('t_1sdshvx18421em', 'tr', 'Ortopedi ve Travmatoloji alanında uzmanlık eğitimi tamamlanarak Ortopedi Uzmanı unvanı alındı.', 'about', 'text'),
('t_1sdshvx18421em', 'en', 'Completed specialization training in Orthopedics and Traumatology, earning the title of Orthopedic Specialist.', 'about', 'text'),
('t_y6ryku1bzyhi8', 'tr', 'İstanbul Üniversitesi Cerrahpaşa Tıp Fakültesi (2011)', 'about', 'text'),
('t_y6ryku1bzyhi8', 'en', 'Istanbul University Cerrahpaşa Faculty of Medicine (2011)', 'about', 'text'),
('t_1g0gmmn156w1ht', 'tr', 'Ortopedi ve Travmatoloji İhtisası', 'about', 'text'),
('t_1g0gmmn156w1ht', 'en', 'Orthopedics and Traumatology Specialization', 'about', 'text'),
('t_01ka3o2rxdaiv', 'tr', 'İstanbul Tıp Fakültesi''nden mezun olarak Tıp Doktoru unvanı alındı.', 'about', 'text'),
('t_01ka3o2rxdaiv', 'en', 'Graduated from Istanbul Faculty of Medicine, earning the title of Doctor of Medicine.', 'about', 'text'),
('t_18uux3p1p7lkyw', 'tr', 'Mezuniyet, 2004', 'about', 'text'),
('t_18uux3p1p7lkyw', 'en', 'Graduation, 2004', 'about', 'text'),
('t_16rfyv710wcvn8', 'tr', 'Tıp Doktoru (İstanbul Üniversitesi)', 'about', 'text'),
('t_16rfyv710wcvn8', 'en', 'Doctor of Medicine (Istanbul University)', 'about', 'text'),
('t_18sla7673ilw5', 'tr', 'Kariyer ve Eğitim Kilometre Taşları', 'about', 'text'),
('t_18sla7673ilw5', 'en', 'Career and Education Milestones', 'about', 'text'),
('t_058r9t215ef0r', 'tr', 'Deneyim ve Akademik Gelişim', 'about', 'text'),
('t_058r9t215ef0r', 'en', 'Experience and Academic Development', 'about', 'text'),
('t_0d2mov3ko9mdp', 'tr', 'Kariyer Yolculuğu', 'about', 'text'),
('t_0d2mov3ko9mdp', 'en', 'Career Journey', 'about', 'text'),
('t_7yd0vj18g2xtq', 'tr', 'Tedavi ve Cerrahi Alanları', 'about', 'text'),
('t_7yd0vj18g2xtq', 'en', 'Treatment and Surgical Areas', 'about', 'text'),
('t_0oucxvyoxqgg8', 'tr', 'Uzmanlık Alanları', 'about', 'text'),
('t_0oucxvyoxqgg8', 'en', 'Areas of Expertise', 'about', 'text'),
('t_13g1ytz15aoe7q', 'tr', '```', 'about', 'text'),
('t_13g1ytz15aoe7q', 'en', '```', 'about', 'text'),
('t_1mkjo3v1ff8x5z', 'tr', 'Halen hasta kabulüne devam etmektedir', 'about', 'text'),
('t_1mkjo3v1ff8x5z', 'en', 'Continues to see patients', 'about', 'text'),
('t_1qnnra9w814f6', 'tr', 'İstanbul Ataköy Kliniği', 'about', 'text'),
('t_1qnnra9w814f6', 'en', 'Istanbul Ataköy Clinic', 'about', 'text'),
('t_0dg054q5cttas', 'tr', 'Akademik Çalışmalar, Doktor Öğretim Üyesi', 'about', 'text'),
('t_0dg054q5cttas', 'en', 'Academic Work, Faculty Member', 'about', 'text'),
('t_10sr85w16se7k', 'tr', 'Akademik Çalışmalar, Yardımcı Doçent', 'about', 'text'),
('t_10sr85w16se7k', 'en', 'Academic Work, Assistant Professor', 'about', 'text'),
('t_14kpp2v13oy1hs', 'tr', 'Özel Medicine Hospital (2013-2025)', 'about', 'text'),
('t_14kpp2v13oy1hs', 'en', 'Özel Medicine Hospital (2013-2025)', 'about', 'text'),
('t_1u2upg11ui25ai', 'tr', 'Eklem Protez ve Artroskopik Cerrahi', 'about', 'text'),
('t_1u2upg11ui25ai', 'en', 'Joint Replacement and Arthroscopic Surgery', 'about', 'text'),
('t_nj7lsj17cfnzc', 'tr', 'Ortopedi Uzmanı', 'about', 'text'),
('t_nj7lsj17cfnzc', 'en', 'Orthopedic Specialist', 'about', 'text'),
('t_1hqvwlk14t0rji', 'tr', 'Kurumsal Görevler ve Deneyim', 'about', 'text'),
('t_1hqvwlk14t0rji', 'en', 'Institutional Roles and Experience', 'about', 'text'),
('t_064mene3e89kp', 'tr', 'Akademisyenlik', 'about', 'text'),
('t_064mene3e89kp', 'en', 'Academic Career', 'about', 'text'),
('t_xhgljw1ri54jp', 'tr', '2011 - 2013', 'about', 'text'),
('t_xhgljw1ri54jp', 'en', '2011 - 2013', 'about', 'text'),
('t_1js85p614wcpge', 'tr', 'Nusaybin Devlet Hastanesi', 'about', 'text'),
('t_1js85p614wcpge', 'en', 'Nusaybin State Hospital', 'about', 'text'),
('t_xx9osi1flobm2', 'tr', 'Ortopedi Kliniği', 'about', 'text'),
('t_xx9osi1flobm2', 'en', 'Orthopedics Clinic', 'about', 'text'),
('t_0ifa101em6vo6', 'tr', 'İstanbul Üniversitesi (2004)', 'about', 'text'),
('t_0ifa101em6vo6', 'en', 'Istanbul University (2004)', 'about', 'text'),
('t_1phwrm11x1tya4', 'tr', 'Eğitim ve Akademik Kariyer', 'about', 'text'),
('t_1phwrm11x1tya4', 'en', 'Education and Academic Career', 'about', 'text'),
('t_01357pvabj9mp', 'tr', 'Yaklaşık 20 yıllık mesleki tecrübesiyle Ortopedi ve Travmatoloji alanında 10.000’in üzerinde başarılı ameliyat gerçekleştiren Dr. Taha Demir, ileri düzeyde İngilizce bilmektedir. Halen İstanbul Ataköy’deki özel kliniğinde hasta kabul etmeye devam etmektedir.', 'about', 'text'),
('t_01357pvabj9mp', 'en', 'With approximately 20 years of professional experience in Orthopedics and Traumatology, Dr. Taha Demir has performed over 10,000 successful surgeries and has an advanced level of English. He continues to see patients at his private clinic in Ataköy, Istanbul.', 'about', 'text'),
('t_t533nr1wdviuv', 'tr', '2013 yılında Özel Medicine Hospital’de çalışmaya başlayan Dr. Taha Demir, burada 12 yıl boyunca hizmet vermiştir. Bu süreçte, Yardımcı Doçent ve Doktor Öğretim Üyesi unvanlarıyla Biruni Üniversitesi ve Atlas Üniversitesi’nde akademik çalışmalar yürütmüştür.', 'about', 'text'),
('t_t533nr1wdviuv', 'en', 'Dr. Taha Demir began working at Özel Medicine Hospital in 2013 and served there for 12 years. During this time, he carried out academic work at Biruni University and Atlas University as an Assistant Professor and Faculty Member.', 'about', 'text'),
('t_0coe1rvjnncah', 'tr', 'Cerrahi ve Klinik Tecrübe', 'about', 'text'),
('t_0coe1rvjnncah', 'en', 'Surgical and Clinical Experience', 'about', 'text'),
('t_1k18jsqna930d', 'tr', '20+ Yıl', 'about', 'text'),
('t_1k18jsqna930d', 'en', '20+ Years', 'about', 'text'),
('t_1kz0y581gtbecd', 'tr', 'Randevu için arayın / WhatsApp', 'about', 'text'),
('t_1kz0y581gtbecd', 'en', 'Call for appointment / WhatsApp', 'about', 'text'),
('t_1mw3bd86jf8bh', 'tr', 'breadcrumb', 'about', 'attr'),
('t_1mw3bd86jf8bh', 'en', 'breadcrumb', 'about', 'attr'),
('t_1m65dd0v1iiki', 'tr', 'Dr. Taha Demir, Ortopedi ve Travmatoloji Uzmanı. Eklem protez cerrahisi, artroskopik cerrahi ve daha fazlası için İstanbul Ataköy''deki kliniğinden randevu alın.', 'about', 'description'),
('t_1m65dd0v1iiki', 'en', 'Dr. Taha Demir, Ortopedi ve Travmatoloji Uzmanı. Eklem protez cerrahisi, artroskopik cerrahi ve daha fazlası için İstanbul Ataköy''deki kliniğinden randevu alın.', 'about', 'description'),
('t_1ulbqx51valuz8', 'tr', 'Dr. Taha Demir, Ortopedi ve Travmatoloji, Eklem Protez Cerrahisi, Artroskopik Cerrahi, İstanbul Ataköy', 'about', 'keywords'),
('t_1ulbqx51valuz8', 'en', 'Dr. Taha Demir, Ortopedi ve Travmatoloji, Eklem Protez Cerrahisi, Artroskopik Cerrahi, İstanbul Ataköy', 'about', 'keywords'),
('t_1flhg57oaxt8q', 'tr', 'Dr. Taha Demir | Hakkımda | Ortopedi ve Travmatoloji Uzmanı', 'about', 'title'),
('t_1flhg57oaxt8q', 'en', 'Dr. Taha Demir | About Me | Orthopedics and Traumatology Specialist', 'about', 'title'),
('t_1ppq7x01aq1sxq', 'tr', ', All Right Reserved.', 'service', 'text'),
('t_1ppq7x01aq1sxq', 'en', ', All Rights Reserved.', 'service', 'text'),
('t_1ph6botk4nbt0', 'tr', 'Bakırköy, İstanbul', 'service', 'text'),
('t_1ph6botk4nbt0', 'en', 'Bakırköy, İstanbul', 'service', 'text'),
('t_1bnlmjq1g0zt78', 'tr', '10:00 – 14:00', 'service', 'text'),
('t_1bnlmjq1g0zt78', 'en', '10:00 – 14:00', 'service', 'text'),
('t_1vuqwrmh1easo', 'tr', '10:00 – 18:00', 'service', 'text'),
('t_1vuqwrmh1easo', 'en', '10:00 – 18:00', 'service', 'text'),
('t_kmo94f176w52r', 'tr', 'Cerrahi Tedaviler', 'service', 'text'),
('t_kmo94f176w52r', 'en', 'Surgical Treatments', 'service', 'text'),
('t_1omm913122ay48', 'tr', 'Dr. Taha Demir ile bugün randevunuzu planlayın.', 'service', 'text'),
('t_1omm913122ay48', 'en', 'Schedule your appointment with Dr. Taha Demir today.', 'service', 'text'),
('t_0slzg1yns9jh2', 'tr', 'Eklem protez cerrahisi, artroskopik cerrahi ve spor yaralanmalarında ileri düzey eğitim.', 'service', 'text'),
('t_0slzg1yns9jh2', 'en', 'Advanced training in joint replacement surgery, arthroscopic surgery, and sports injuries.', 'service', 'text'),
('t_15141nj10vxvbe', 'tr', 'Dr. Taha Demir, fonksiyonel iyileşmeye odaklı kapsamlı cerrahi bakım sunar.', 'service', 'text'),
('t_15141nj10vxvbe', 'en', 'Dr. Taha Demir provides comprehensive surgical care focused on functional recovery.', 'service', 'text'),
('t_0e844dh18oean', 'tr', 'Hassasiyet. Fonksiyon. Güven. Hasta odaklı ve etik yaklaşımla güvenli, doğal ve en iyi sonuçlar için.', 'service', 'text'),
('t_0e844dh18oean', 'en', 'Precision. Function. Trust. For safe, natural, and optimal results with a patient-centered and ethical approach.', 'service', 'text'),
('t_0yhw5gzdrsok6', 'tr', 'Uzman Ortopedi Konsültasyonuna mı İhtiyacınız Var?', 'service', 'text'),
('t_0yhw5gzdrsok6', 'en', 'Need an Expert Orthopedic Consultation?', 'service', 'text'),
('t_15z3wbmyw5758', 'tr', 'Kök hücre, eksozom ve PRP tedavileri ile eklem kıkırdağı ve yumuşak doku iyileşmesi desteklenir.', 'service', 'text'),
('t_15z3wbmyw5758', 'en', 'Joint cartilage and soft tissue healing are supported with stem cell, exosome, and PRP treatments.', 'service', 'text'),
('t_15ao3aykir50o', 'tr', 'Bağ, menisküs ve tendon yaralanmalarında sporcuya özel cerrahi tedavi ve rehabilitasyon planı uygulanır.', 'service', 'text'),
('t_15ao3aykir50o', 'en', 'A surgical treatment and rehabilitation plan tailored to the athlete is applied for ligament, meniscus, and tendon injuries.', 'service', 'text'),
('t_1ptkcha82tjvb', 'tr', 'Travma sonrası oluşan kırık ve çıkıklar, modern osteosentez teknikleriyle hızlı iyileşme sağlanacak şekilde tedavi edilir.', 'service', 'text'),
('t_1ptkcha82tjvb', 'en', 'Post-traumatic fractures and dislocations are treated with modern osteosynthesis techniques to ensure rapid recovery.', 'service', 'text'),
('t_01uzhtg48r2rr', 'tr', 'El ve el bileğindeki yaralanmalar, sinir sıkışmaları ve tendon sorunları mikrocerrahi teknikleriyle tedavi edilir.', 'service', 'text'),
('t_01uzhtg48r2rr', 'en', 'Injuries, nerve compressions, and tendon problems in the hand and wrist are treated using microsurgical techniques.', 'service', 'text'),
('t_fjx9w016h7vo6', 'tr', 'Çocuklarda gelişimsel kalça displazisi, ayak deformiteleri ve kırıklar erken teşhis ile başarıyla tedavi edilir.', 'service', 'text'),
('t_fjx9w016h7vo6', 'en', 'Developmental hip dysplasia, foot deformities, and fractures in children are successfully treated with early diagnosis.', 'service', 'text'),
('t_dkyxx91kv804x', 'tr', 'Kemik ve yumuşak dokuda gelişen tümörler; şişlik, ağrı ve kırık riskini ortadan kaldıracak şekilde cerrahi olarak tedavi edilir.', 'service', 'text'),
('t_dkyxx91kv804x', 'en', 'Tumors developing in bone and soft tissue are surgically treated to eliminate swelling, pain, and fracture risk.', 'service', 'text'),
('t_0ddjp0tn7ewfo', 'tr', 'Planlı kemik uzatma teknikleriyle güvenli ve kontrollü şekilde boy uzatma ve vücut oranı düzeltme cerrahisi uygulanır.', 'service', 'text'),
('t_0ddjp0tn7ewfo', 'en', 'Height lengthening and body proportion correction surgery is performed safely and in a controlled manner using planned bone lengthening techniques.', 'service', 'text'),
('t_17w0jvt1a4poem', 'tr', 'Doğuştan ya da sonradan gelişen kemik ve eklem deformiteleri düzeltilerek hem fonksiyon hem estetik görünüm iyileştirilir.', 'service', 'text'),
('t_17w0jvt1a4poem', 'en', 'Congenital or acquired bone and joint deformities are corrected, improving both function and appearance.', 'service', 'text'),
('t_0t7h9m65m6arc', 'tr', 'Bel ve boyun fıtığı, sinir sıkışması ve omurga şekil bozukluklarında modern cerrahi teknikler uygulanır.', 'service', 'text'),
('t_0t7h9m65m6arc', 'en', 'Modern surgical techniques are applied for lumbar and cervical disc herniation, nerve compression, and spinal deformities.', 'service', 'text'),
('t_2znk5y11nmxci', 'tr', 'Ayak ve ayak bileğinde travma, deformite, kireçlenme ve spor yaralanmalarına bağlı ağrı ve hareket kısıtlılığı cerrahi olarak giderilir.', 'service', 'text'),
('t_2znk5y11nmxci', 'en', 'Pain and limited mobility in the foot and ankle caused by trauma, deformity, arthritis, and sports injuries are surgically resolved.', 'service', 'text'),
('t_0szzdqtf2yg9j', 'tr', 'Omuz ve dirsekteki tendon kopmaları, eklem aşınmaları ve sıkışmalar modern cerrahi yöntemlerle tedavi edilerek eklem fonksiyonları geri kazandırılır.', 'service', 'text'),
('t_0szzdqtf2yg9j', 'en', 'Tendon tears, joint wear, and impingements in the shoulder and elbow are treated with modern surgical methods, restoring joint function.', 'service', 'text'),
('t_fr8ynm1ssogn2', 'tr', 'Küçük kesilerle uygulanan kapalı yöntemle eklem içi problemler teşhis edilir ve aynı seansta tedavi edilir; iyileşme süresi kısalır.', 'service', 'text'),
('t_fr8ynm1ssogn2', 'en', 'Using small incisions, this keyhole method diagnoses and treats problems inside the joint in the same session, shortening recovery time.', 'service', 'text'),
('t_1tugjy2108h0gj', 'tr', 'Diz protezi; ciddi hasar, kireçlenme, romatoid artrit veya travma sonrası oluşan eklem bozukluklarında uygulanır. Hasarlı eklemin yerini yapay eklem alır, ağrı azalır ve hareket kabiliyeti artar.', 'service', 'text'),
('t_1tugjy2108h0gj', 'en', 'Knee replacement is performed for joint disorders caused by severe damage, arthritis, rheumatoid arthritis, or trauma. The damaged joint is replaced with an artificial joint, reducing pain and increasing mobility.', 'service', 'text'),
('t_1b7rvik1e31u0p', 'tr', 'Kalça protezi, kireçlenme, romatoid artrit ya da travma sonrası gelişen hasarlar nedeniyle yaşanan şiddetli ağrı ve hareket kısıtlılığına kesin çözüm sunar. Hasarlı eklem yapay bir eklemle değiştirilir; ağrı hafifler ve hareket kabiliyeti geri kazanılır.', 'service', 'text'),
('t_1b7rvik1e31u0p', 'en', 'Hip replacement offers a definitive solution for severe pain and limited mobility caused by arthritis, rheumatoid arthritis, or post-traumatic damage. The damaged joint is replaced with an artificial joint, relieving pain and restoring mobility.', 'service', 'text'),
('t_0z24vc32qhbcl', 'tr', 'Dr. Taha Demir tarafından sunulan Ortopedi ve Travmatoloji tedavileri: eklem protez cerrahisi, artroskopik cerrahi, spor yaralanmaları ve daha fazlası, İstanbul Ataköy.', 'service', 'description'),
('t_0z24vc32qhbcl', 'en', 'Dr. Taha Demir tarafından sunulan Ortopedi ve Travmatoloji tedavileri: eklem protez cerrahisi, artroskopik cerrahi, spor yaralanmaları ve daha fazlası, İstanbul Ataköy.', 'service', 'description'),
('t_1f3bfahrw0egk', 'tr', 'Dr. Taha Demir, Ortopedi ve Travmatoloji, eklem protez cerrahisi, artroskopik cerrahi, İstanbul Ataköy', 'service', 'keywords'),
('t_1f3bfahrw0egk', 'en', 'Dr. Taha Demir, Ortopedi ve Travmatoloji, eklem protez cerrahisi, artroskopik cerrahi, İstanbul Ataköy', 'service', 'keywords'),
('t_15hxswbwmom6j', 'tr', 'Dr. Taha Demir | Tedaviler | Ortopedi ve Travmatoloji Uzmanı', 'service', 'title'),
('t_15hxswbwmom6j', 'en', 'Dr. Taha Demir | Treatments | Orthopedics and Traumatology Specialist', 'service', 'title'),
('t_13zb6y11rnunw1', 'tr', 'Expanded view', 'gallery', 'attr'),
('t_13zb6y11rnunw1', 'en', 'Expanded view', 'gallery', 'attr'),
('t_hd25ff1bfye86', 'tr', 'Deformite Ameliyatı - Dr. Taha Demir 22', 'gallery', 'attr'),
('t_hd25ff1bfye86', 'en', 'Deformite Ameliyatı - Dr. Taha Demir 22', 'gallery', 'attr'),
('t_1wt1w8byqt1kh', 'tr', 'Diz Protezi Ameliyatı - Dr. Taha Demir 21', 'gallery', 'attr'),
('t_1wt1w8byqt1kh', 'en', 'Diz Protezi Ameliyatı - Dr. Taha Demir 21', 'gallery', 'attr'),
('t_5ix2tr1lun97k', 'tr', 'Kalça Protezi Ameliyatı - Dr. Taha Demir 20', 'gallery', 'attr'),
('t_5ix2tr1lun97k', 'en', 'Kalça Protezi Ameliyatı - Dr. Taha Demir 20', 'gallery', 'attr'),
('t_0hn4wmd5rnoke', 'tr', 'Deformite Ameliyatı - Dr. Taha Demir 19', 'gallery', 'attr'),
('t_0hn4wmd5rnoke', 'en', 'Deformite Ameliyatı - Dr. Taha Demir 19', 'gallery', 'attr'),
('t_0vcv7ormxgmd3', 'tr', 'Diz Protezi Ameliyatı - Dr. Taha Demir 18', 'gallery', 'attr'),
('t_0vcv7ormxgmd3', 'en', 'Diz Protezi Ameliyatı - Dr. Taha Demir 18', 'gallery', 'attr'),
('t_18n1dj59lru4s', 'tr', 'Kalça Protezi Ameliyatı - Dr. Taha Demir 17', 'gallery', 'attr'),
('t_18n1dj59lru4s', 'en', 'Kalça Protezi Ameliyatı - Dr. Taha Demir 17', 'gallery', 'attr'),
('t_hx4ibc13n2j77', 'tr', 'Deformite Ameliyatı - Dr. Taha Demir 16', 'gallery', 'attr'),
('t_hx4ibc13n2j77', 'en', 'Deformite Ameliyatı - Dr. Taha Demir 16', 'gallery', 'attr')
ON CONFLICT (key, lang) DO NOTHING;

INSERT INTO public.site_texts (key, lang, value, page, kind) VALUES
('t_tyx77w1135cqw', 'tr', 'Diz Protezi Ameliyatı - Dr. Taha Demir 15', 'gallery', 'attr'),
('t_tyx77w1135cqw', 'en', 'Diz Protezi Ameliyatı - Dr. Taha Demir 15', 'gallery', 'attr'),
('t_17t2kg817h6orl', 'tr', 'Kalça Protezi Ameliyatı - Dr. Taha Demir 14', 'gallery', 'attr'),
('t_17t2kg817h6orl', 'en', 'Kalça Protezi Ameliyatı - Dr. Taha Demir 14', 'gallery', 'attr'),
('t_jb2is71uxwof0', 'tr', 'Deformite Ameliyatı - Dr. Taha Demir 13', 'gallery', 'attr'),
('t_jb2is71uxwof0', 'en', 'Deformite Ameliyatı - Dr. Taha Demir 13', 'gallery', 'attr'),
('t_0toxlixd2lk8l', 'tr', 'Diz Protezi Ameliyatı - Dr. Taha Demir 12', 'gallery', 'attr'),
('t_0toxlixd2lk8l', 'en', 'Diz Protezi Ameliyatı - Dr. Taha Demir 12', 'gallery', 'attr'),
('t_1970kx31ys0tze', 'tr', 'Kalça Protezi Ameliyatı - Dr. Taha Demir 11', 'gallery', 'attr'),
('t_1970kx31ys0tze', 'en', 'Kalça Protezi Ameliyatı - Dr. Taha Demir 11', 'gallery', 'attr'),
('t_0jl24h6ts7h2p', 'tr', 'Deformite Ameliyatı - Dr. Taha Demir 10', 'gallery', 'attr'),
('t_0jl24h6ts7h2p', 'en', 'Deformite Ameliyatı - Dr. Taha Demir 10', 'gallery', 'attr'),
('t_1bgu68pyaxb3x', 'tr', 'Diz Protezi Ameliyatı - Dr. Taha Demir 9', 'gallery', 'attr'),
('t_1bgu68pyaxb3x', 'en', 'Diz Protezi Ameliyatı - Dr. Taha Demir 9', 'gallery', 'attr'),
('t_c5g1sn15n7278', 'tr', 'Kalça Protezi Ameliyatı - Dr. Taha Demir 8', 'gallery', 'attr'),
('t_c5g1sn15n7278', 'en', 'Kalça Protezi Ameliyatı - Dr. Taha Demir 8', 'gallery', 'attr'),
('t_0ksp4skbn0auz', 'tr', 'Deformite Ameliyatı - Dr. Taha Demir 7', 'gallery', 'attr'),
('t_0ksp4skbn0auz', 'en', 'Deformite Ameliyatı - Dr. Taha Demir 7', 'gallery', 'attr'),
('t_1dyqlhgguy80m', 'tr', 'Diz Protezi Ameliyatı - Dr. Taha Demir 6', 'gallery', 'attr'),
('t_1dyqlhgguy80m', 'en', 'Diz Protezi Ameliyatı - Dr. Taha Demir 6', 'gallery', 'attr'),
('t_08jl7s0o77z3x', 'tr', 'Kalça Protezi Ameliyatı - Dr. Taha Demir 5', 'gallery', 'attr'),
('t_08jl7s0o77z3x', 'en', 'Kalça Protezi Ameliyatı - Dr. Taha Demir 5', 'gallery', 'attr'),
('t_lmnxvh19if5hs', 'tr', 'Deformite Ameliyatı - Dr. Taha Demir 4', 'gallery', 'attr'),
('t_lmnxvh19if5hs', 'en', 'Deformite Ameliyatı - Dr. Taha Demir 4', 'gallery', 'attr'),
('t_1d4rsej185sd8f', 'tr', 'Diz Protezi Ameliyatı - Dr. Taha Demir 3', 'gallery', 'attr'),
('t_1d4rsej185sd8f', 'en', 'Diz Protezi Ameliyatı - Dr. Taha Demir 3', 'gallery', 'attr'),
('t_ahifmt1m2mtqq', 'tr', 'Kalça Protezi Ameliyatı - Dr. Taha Demir 2', 'gallery', 'attr'),
('t_ahifmt1m2mtqq', 'en', 'Kalça Protezi Ameliyatı - Dr. Taha Demir 2', 'gallery', 'attr'),
('t_0k8pxemexankh', 'tr', 'Deformite Ameliyatı - Dr. Taha Demir 1', 'gallery', 'attr'),
('t_0k8pxemexankh', 'en', 'Deformite Ameliyatı - Dr. Taha Demir 1', 'gallery', 'attr'),
('t_t34uxy1meog10', 'tr', 'İptal', 'gallery', 'text'),
('t_t34uxy1meog10', 'en', 'Cancel', 'gallery', 'text'),
('t_1q1bb5t1osojp0', 'tr', 'Evet, Görüntüle', 'gallery', 'text'),
('t_1q1bb5t1osojp0', 'en', 'Yes, View', 'gallery', 'text'),
('t_1lubpwv1qyonua', 'tr', 'এই গ্যালারিতে রক্তাক্ত বা সংবেদনশীল চিত্র থাকতে পারে যা কিছু দর্শকের জন্য অস্বস্তিকর হতে পারে।', 'gallery', 'text'),
('t_1lubpwv1qyonua', 'en', 'This gallery may contain graphic or sensitive images that may be uncomfortable for some viewers.', 'gallery', 'text'),
('t_1pm0k81wap09g', 'tr', 'আপনি কি এগিয়ে যেতে চান?', 'gallery', 'text'),
('t_1pm0k81wap09g', 'en', 'আপনি কি এগিয়ে যেতে চান?', 'gallery', 'text'),
('t_0wldcene2hew1', 'tr', 'Uyarı', 'gallery', 'text'),
('t_0wldcene2hew1', 'en', 'Warning', 'gallery', 'text'),
('t_07thjtp7krl9b', 'tr', 'Dr. Taha Demir''in Ortopedi ve Travmatoloji alanındaki ameliyat ve tedavi görselleri, İstanbul Ataköy.', 'gallery', 'description'),
('t_07thjtp7krl9b', 'en', 'Dr. Taha Demir''in Ortopedi ve Travmatoloji alanındaki ameliyat ve tedavi görselleri, İstanbul Ataköy.', 'gallery', 'description'),
('t_9znql21ymrote', 'tr', 'Dr. Taha Demir, Ortopedi ve Travmatoloji, eklem protez, artroskopik cerrahi, İstanbul Ataköy, ameliyat görselleri', 'gallery', 'keywords'),
('t_9znql21ymrote', 'en', 'Dr. Taha Demir, Ortopedi ve Travmatoloji, eklem protez, artroskopik cerrahi, İstanbul Ataköy, ameliyat görselleri', 'gallery', 'keywords'),
('t_00ppwmux53rdb', 'tr', 'Dr. Taha Demir | Ameliyat Görselleri | Ortopedi ve Travmatoloji Uzmanı', 'gallery', 'title'),
('t_00ppwmux53rdb', 'en', 'Dr. Taha Demir | Surgery Images | Orthopedics and Traumatology Specialist', 'gallery', 'title'),
('t_1u4ln6ek9f9lf', 'tr', '© 2026', 'appoinment', 'text'),
('t_1u4ln6ek9f9lf', 'en', '© 2026', 'appoinment', 'text'),
('t_0bnli6g4vdynf', 'tr', '- Tüm hakları saklıdır.', 'appoinment', 'text'),
('t_0bnli6g4vdynf', 'en', '- All rights reserved.', 'appoinment', 'text'),
('t_htc7ob1rw20oq', 'tr', 'Pazar:', 'appoinment', 'text'),
('t_htc7ob1rw20oq', 'en', 'Sunday:', 'appoinment', 'text'),
('t_0nuvmbaa9sdfh', 'tr', 'Cumartesi:', 'appoinment', 'text'),
('t_0nuvmbaa9sdfh', 'en', 'Saturday:', 'appoinment', 'text'),
('t_1cptvsj1wwvcw1', 'tr', 'Pazartesi - Cuma:', 'appoinment', 'text'),
('t_1cptvsj1wwvcw1', 'en', 'Monday - Friday:', 'appoinment', 'text'),
('t_puufbw1we8nkm', 'tr', 'Ataköy Towers, A blok, Kat 4, No 79, PK:34158, Bakırköy/İstanbul', 'appoinment', 'text'),
('t_puufbw1we8nkm', 'en', 'Ataköy Towers, A blok, Kat 4, No 79, PK:34158, Bakırköy/İstanbul', 'appoinment', 'text'),
('t_5eee6e1xtq8qs', 'tr', 'Ataköy, İstanbul', 'appoinment', 'text'),
('t_5eee6e1xtq8qs', 'en', 'Ataköy, İstanbul', 'appoinment', 'text'),
('t_06wm3g5qndcip', 'tr', 'Tüm tedavi bilgileriniz güvenle saklanır', 'appoinment', 'text'),
('t_06wm3g5qndcip', 'en', 'All your treatment information is stored securely', 'appoinment', 'text'),
('t_1pukq3t17l96bl', 'tr', 'Kayıt Saklama', 'appoinment', 'text'),
('t_1pukq3t17l96bl', 'en', 'Record Keeping', 'appoinment', 'text'),
('t_02e9q1mz846k1', 'tr', 'Randevunuzdan önce size hatırlatma yapılır', 'appoinment', 'text'),
('t_02e9q1mz846k1', 'en', 'You will be reminded before your appointment', 'appoinment', 'text'),
('t_0174aca86e0et', 'tr', 'Otomatik Hatırlatma', 'appoinment', 'text'),
('t_0174aca86e0et', 'en', 'Automatic Reminder', 'appoinment', 'text'),
('t_1euk0r71guq79l', 'tr', 'Beklemek yerine hızlıca iletişime geçip randevunuzu alın', 'appoinment', 'text'),
('t_1euk0r71guq79l', 'en', 'Get in touch quickly and book your appointment instead of waiting', 'appoinment', 'text'),
('t_14hvj8y1ekr168', 'tr', 'Zaman Kazanın', 'appoinment', 'text'),
('t_14hvj8y1ekr168', 'en', 'Save Time', 'appoinment', 'text'),
('t_1dz8z4ncm8y3p', 'tr', 'Evden ayrılmadan telefon veya WhatsApp ile randevunuzu oluşturun', 'appoinment', 'text'),
('t_1dz8z4ncm8y3p', 'en', 'Book your appointment by phone or WhatsApp without leaving home', 'appoinment', 'text'),
('t_1e8lgho1ipsb40', 'tr', 'Kolay Erişim', 'appoinment', 'text'),
('t_1e8lgho1ipsb40', 'en', 'Easy Access', 'appoinment', 'text'),
('t_1vul4et1szqeby', 'tr', 'Randevu Almanın Avantajları', 'appoinment', 'text'),
('t_1vul4et1szqeby', 'en', 'Benefits of Booking an Appointment', 'appoinment', 'text'),
('t_1sgb6k2jl9hjr', 'tr', 'Asistan: 0532 690 54 24', 'appoinment', 'text'),
('t_1sgb6k2jl9hjr', 'en', 'Assistant: 0532 690 54 24', 'appoinment', 'text'),
('t_8vgxg11qd9fue', 'tr', 'WhatsApp''tan Randevu Al', 'appoinment', 'text'),
('t_8vgxg11qd9fue', 'en', 'Book Appointment via WhatsApp', 'appoinment', 'text'),
('t_4r441r1czu1wi', 'tr', 'Tedavi sonrası takip desteği ve danışmanlık', 'appoinment', 'text'),
('t_4r441r1czu1wi', 'en', 'Post-treatment follow-up support and consultation', 'appoinment', 'text'),
('t_0pyd2xp2fyupr', 'tr', 'Takip Desteği', 'appoinment', 'text'),
('t_0pyd2xp2fyupr', 'en', 'Follow-up Support', 'appoinment', 'text'),
('t_016fuxlnpise4', 'tr', 'Tüm yazışmalarınız dijital olarak saklanır', 'appoinment', 'text'),
('t_016fuxlnpise4', 'en', 'All your correspondence is stored digitally', 'appoinment', 'text'),
('t_1vbxpkqmcq61s', 'tr', 'Dijital Kayıt', 'appoinment', 'text'),
('t_1vbxpkqmcq61s', 'en', 'Digital Record', 'appoinment', 'text'),
('t_1qr8tpao65v02', 'tr', 'Size uygun zamanda randevunuzu oluşturun', 'appoinment', 'text'),
('t_1qr8tpao65v02', 'en', 'Book your appointment at a time that suits you', 'appoinment', 'text'),
('t_1mh5m7z1rhqrgu', 'tr', 'Esnek Zamanlama', 'appoinment', 'text'),
('t_1mh5m7z1rhqrgu', 'en', 'Flexible Scheduling', 'appoinment', 'text'),
('t_3sja3d19rt5ma', 'tr', 'Asistanımızdan hızlı ve doğru yönlendirme alın', 'appoinment', 'text'),
('t_3sja3d19rt5ma', 'en', 'Get quick and accurate guidance from our assistant', 'appoinment', 'text'),
('t_1r4hlm91wsua1r', 'tr', 'Uzman Danışmanlık', 'appoinment', 'text'),
('t_1r4hlm91wsua1r', 'en', 'Expert Consultation', 'appoinment', 'text'),
('t_0dyzb0o96lybo', 'tr', 'Asistanımızla doğrudan WhatsApp üzerinden iletişime geçin', 'appoinment', 'text'),
('t_0dyzb0o96lybo', 'en', 'Contact our assistant directly via WhatsApp', 'appoinment', 'text'),
('t_1phznm01wqu234', 'tr', 'WhatsApp ile Randevu', 'appoinment', 'text'),
('t_1phznm01wqu234', 'en', 'Appointment via WhatsApp', 'appoinment', 'text'),
('t_1yaodqh164l0a8', 'tr', 'Tavsiye Edilen', 'appoinment', 'text'),
('t_1yaodqh164l0a8', 'en', 'Recommended', 'appoinment', 'text'),
('t_f9vgt113z6mvf', 'tr', '2', 'appoinment', 'text'),
('t_f9vgt113z6mvf', 'en', '2', 'appoinment', 'text'),
('t_1im790w176mzs0', 'tr', 'Dr. İletişim: 0532 171 78 40', 'appoinment', 'text'),
('t_1im790w176mzs0', 'en', 'Doctor Contact: 0532 171 78 40', 'appoinment', 'text'),
('t_1cc0n991msyekd', 'tr', 'Randevu için Ara', 'appoinment', 'text'),
('t_1cc0n991msyekd', 'en', 'Call for Appointment', 'appoinment', 'text'),
('t_0gqctm39a8agg', 'tr', 'Doğrudan doktor iletişim hattı ile güvenli görüşme', 'appoinment', 'text'),
('t_0gqctm39a8agg', 'en', 'Secure conversation through a direct doctor contact line', 'appoinment', 'text'),
('t_9025fg1e7yp9f', 'tr', 'Güvenilir İletişim', 'appoinment', 'text'),
('t_9025fg1e7yp9f', 'en', 'Reliable Communication', 'appoinment', 'text'),
('t_1lrzrqreng7g9', 'tr', 'Çalışma saatleri içinde dilediğiniz an arayın', 'appoinment', 'text'),
('t_1lrzrqreng7g9', 'en', 'Call anytime during working hours', 'appoinment', 'text'),
('t_0er0ggp6q8xd1', 'tr', 'Esnek Saatler', 'appoinment', 'text'),
('t_0er0ggp6q8xd1', 'en', 'Flexible Hours', 'appoinment', 'text'),
('t_1bicm0p1oge9w0', 'tr', 'Telefonda tedaviniz hakkında ön bilgi alın', 'appoinment', 'text'),
('t_1bicm0p1oge9w0', 'en', 'Get preliminary information about your treatment over the phone', 'appoinment', 'text'),
('t_0hf0qoedcm2bw', 'tr', 'Ön Bilgilendirme', 'appoinment', 'text'),
('t_0hf0qoedcm2bw', 'en', 'Preliminary Information', 'appoinment', 'text'),
('t_1m8eeig1aofmmk', 'tr', 'Tek bir aramayla size uygun zamanı belirleyin', 'appoinment', 'text'),
('t_1m8eeig1aofmmk', 'en', 'Set your preferred time with a single call', 'appoinment', 'text'),
('t_1wbw0jc16vp86k', 'tr', 'Hızlı Randevu', 'appoinment', 'text'),
('t_1wbw0jc16vp86k', 'en', 'Quick Appointment', 'appoinment', 'text'),
('t_16em09mlpiv3i', 'tr', 'Doğrudan klinik ile telefonla iletişime geçin', 'appoinment', 'text'),
('t_16em09mlpiv3i', 'en', 'Contact the clinic directly by phone', 'appoinment', 'text'),
('t_1fo0wzvubfw1o', 'tr', 'Telefon ile Randevu', 'appoinment', 'text'),
('t_1fo0wzvubfw1o', 'en', 'Appointment by Phone', 'appoinment', 'text'),
('t_19ei8hb1bga7a0', 'tr', 'Popüler', 'appoinment', 'text'),
('t_19ei8hb1bga7a0', 'en', 'Popular', 'appoinment', 'text'),
('t_0efwnq463rs8m', 'tr', '1', 'appoinment', 'text'),
('t_0efwnq463rs8m', 'en', '1', 'appoinment', 'text'),
('t_1fyti0evq91jb', 'tr', 'Bize doğrudan telefon veya WhatsApp üzerinden ulaşarak kolayca randevu oluşturabilirsiniz. Aşağıdaki iki iletişim kanalından size uygun olanı seçerek uygun zamanınızı belirleyin.', 'appoinment', 'text'),
('t_1fyti0evq91jb', 'en', 'You can easily book an appointment by contacting us directly via phone or WhatsApp. Choose whichever of the two contact channels below suits you and set your preferred time.', 'appoinment', 'text'),
('t_1kau4n11wytxde', 'tr', 'Online Randevu ve Konsültasyon', 'appoinment', 'text'),
('t_1kau4n11wytxde', 'en', 'Online Appointment and Consultation', 'appoinment', 'text'),
('t_1t35zfsbr65c7', 'tr', 'Randevu', 'appoinment', 'text'),
('t_1t35zfsbr65c7', 'en', 'Appointment', 'appoinment', 'text'),
('t_03dg52fm3qcu6', 'tr', 'Dr. Taha Demir ile randevu oluşturun. Ortopedi ve Travmatoloji Uzmanı, İstanbul Ataköy. Pazartesi-Cuma 10:00–18:00, Cumartesi 10:00–14:00.', 'appoinment', 'description'),
('t_03dg52fm3qcu6', 'en', 'Dr. Taha Demir ile randevu oluşturun. Ortopedi ve Travmatoloji Uzmanı, İstanbul Ataköy. Pazartesi-Cuma 10:00–18:00, Cumartesi 10:00–14:00.', 'appoinment', 'description'),
('t_0ftiqeebrx5ma', 'tr', 'Dr. Taha Demir, randevu, Ortopedi ve Travmatoloji Uzmanı, İstanbul Ataköy, eklem protez, artroskopik cerrahi', 'appoinment', 'keywords'),
('t_0ftiqeebrx5ma', 'en', 'Dr. Taha Demir, randevu, Ortopedi ve Travmatoloji Uzmanı, İstanbul Ataköy, eklem protez, artroskopik cerrahi', 'appoinment', 'keywords'),
('t_1qw5jnc93ue99', 'tr', 'Dr. Taha Demir | Randevu | Ortopedi ve Travmatoloji Uzmanı', 'appoinment', 'title'),
('t_1qw5jnc93ue99', 'en', 'Dr. Taha Demir | Appointment | Orthopedics and Traumatology Specialist', 'appoinment', 'title'),
('t_1ompgwf1jyogeu', 'tr', 'Randevu saatinizden 10-15 dakika önce klinikte olun. Bu sayede formları rahatça doldurabilir ve doktorla görüşmeye hazır olabilirsiniz.', 'contact', 'text'),
('t_1ompgwf1jyogeu', 'en', 'Be at the clinic 10-15 minutes before your appointment time. This way you can comfortably fill out forms and be ready to meet with the doctor.', 'contact', 'text'),
('t_0w5clznrc3g1c', 'tr', 'Zamanında Gelin', 'contact', 'text'),
('t_0w5clznrc3g1c', 'en', 'Arrive on Time', 'contact', 'text'),
('t_119ougc1h3bhyq', 'tr', 'Randevudan önce şikayetinizle ilgili sorularınızı yazın. Böylece unutmadan sorabilir ve sorununuza çözüm bulmanız kolaylaşır.', 'contact', 'text'),
('t_119ougc1h3bhyq', 'en', 'Write down your questions about your complaint before the appointment. This way you won''t forget to ask and it will be easier to find a solution to your problem.', 'contact', 'text'),
('t_1q9re4l1vm7qu8', 'tr', 'Sorularınızı Hazırlayın', 'contact', 'text'),
('t_1q9re4l1vm7qu8', 'en', 'Prepare Your Questions', 'contact', 'text'),
('t_14p0yy09dy0zs', 'tr', 'Randevu gününde önceki tıbbi raporlarınızı, tetkik sonuçlarınızı ve ilaç listenizi yanınızda getirin. Bu, doktorun durumunuzu daha iyi değerlendirmesini sağlar.', 'contact', 'text'),
('t_14p0yy09dy0zs', 'en', 'On the day of your appointment, bring your previous medical reports, test results, and medication list. This helps the doctor better assess your condition.', 'contact', 'text'),
('t_64blec19cxkwt', 'tr', 'Gerekli Belgeleri Yanınızda Getirin', 'contact', 'text'),
('t_64blec19cxkwt', 'en', 'Bring the Necessary Documents', 'contact', 'text'),
('t_1bm5xg91qyi0ci', 'tr', 'Haftanın başında veya sabah saatlerini tercih ederseniz daha hızlı hizmet alabilirsiniz. Hafta sonu ve öğleden sonraları genellikle daha yoğundur.', 'contact', 'text'),
('t_1bm5xg91qyi0ci', 'en', 'If you prefer the beginning of the week or morning hours, you can receive faster service. Weekends and afternoons are usually busier.', 'contact', 'text'),
('t_0kwviuzb250ts', 'tr', 'Doğru Zamanda Randevu Alın', 'contact', 'text'),
('t_0kwviuzb250ts', 'en', 'Book Your Appointment at the Right Time', 'contact', 'text'),
('t_9i0lfc1dhv6qv', 'tr', 'Şikayetinizi açıklayın veya ek bilgi verin', 'contact', 'attr'),
('t_9i0lfc1dhv6qv', 'en', 'Şikayetinizi açıklayın veya ek bilgi verin', 'contact', 'attr'),
('t_sfif0r1kmrpsm', 'tr', 'Mesaj / Şikayet', 'contact', 'text'),
('t_sfif0r1kmrpsm', 'en', 'Message / Complaint', 'contact', 'text'),
('t_0nf3de5nj3ame', 'tr', 'Randevu Tarihi', 'contact', 'text'),
('t_0nf3de5nj3ame', 'en', 'Appointment Date', 'contact', 'text'),
('t_pwhuyd1g3q047', 'tr', 'Telefon numaranızı yazın', 'contact', 'attr'),
('t_pwhuyd1g3q047', 'en', 'Telefon numaranızı yazın', 'contact', 'attr'),
('t_4x9zbq1wr9suy', 'tr', 'Telefon Numarası', 'contact', 'text'),
('t_4x9zbq1wr9suy', 'en', 'Phone Number', 'contact', 'text'),
('t_0d1yn998diteb', 'tr', '*', 'contact', 'text'),
('t_0d1yn998diteb', 'en', '*', 'contact', 'text'),
('t_0ornhp0rrykjd', 'tr', 'Adınızı ve soyadınızı yazın', 'contact', 'attr'),
('t_0ornhp0rrykjd', 'en', 'Adınızı ve soyadınızı yazın', 'contact', 'attr'),
('t_148kalwwhbkb6', 'tr', 'Ad Soyad', 'contact', 'text'),
('t_148kalwwhbkb6', 'en', 'Full Name', 'contact', 'text'),
('t_0edovesx832yb', 'tr', 'Aşağıdaki bilgileri doldurun, sizinle iletişime geçelim', 'contact', 'text'),
('t_0edovesx832yb', 'en', 'Fill in the information below and we will get in touch with you', 'contact', 'text'),
('t_0aht863xdrw73', 'tr', 'Randevu için Dr. Taha Demir ile iletişime geçin. Ortopedi ve Travmatoloji Uzmanı, İstanbul Ataköy''deki kliniğinde hasta kabul etmektedir.', 'contact', 'description'),
('t_0aht863xdrw73', 'en', 'Randevu için Dr. Taha Demir ile iletişime geçin. Ortopedi ve Travmatoloji Uzmanı, İstanbul Ataköy''deki kliniğinde hasta kabul etmektedir.', 'contact', 'description'),
('t_p2p01k1wkbv3r', 'tr', 'Dr. Taha Demir iletişim, randevu, Ortopedi ve Travmatoloji, eklem protez, artroskopik cerrahi, İstanbul Ataköy', 'contact', 'keywords'),
('t_p2p01k1wkbv3r', 'en', 'Dr. Taha Demir iletişim, randevu, Ortopedi ve Travmatoloji, eklem protez, artroskopik cerrahi, İstanbul Ataköy', 'contact', 'keywords'),
('t_0dobl7si8f3gr', 'tr', 'Dr. Taha Demir | İletişim | Ortopedi ve Travmatoloji Uzmanı', 'contact', 'title'),
('t_0dobl7si8f3gr', 'en', 'Dr. Taha Demir | Contact | Orthopedics and Traumatology Specialist', 'contact', 'title')
ON CONFLICT (key, lang) DO NOTHING;

INSERT INTO public.site_images (slot, url, page) VALUES
('dr-taha-logo', '/__l5e/assets-v1/8883d805-df3a-47df-a527-456d246398c9/dr-taha-logo-2026.png', 'index'),
('video-thumb-tr', '/__l5e/assets-v1/13ffe17e-abc6-4165-b663-8d21bee4ade8/video-thumb-tr.png', 'index'),
('service-prp', '/site/img/service-prp.jpg', 'index'),
('service-spor', '/site/img/service-spor.jpg', 'index'),
('service-kirik', '/site/img/service-kirik.jpg', 'index'),
('service-el', '/site/img/service-el.jpg', 'index'),
('service-cocuk', '/site/img/service-cocuk.jpg', 'index'),
('service-tumor', '/site/img/service-tumor.jpg', 'index'),
('service-boy-uzatma', '/site/img/service-boy-uzatma.jpg', 'index'),
('service-deformite', '/site/img/service-deformite.jpg', 'index'),
('service-omurga', '/site/img/service-omurga.jpg', 'index'),
('service-ayak-bilek', '/site/img/service-ayak-bilek.jpg', 'index'),
('service-omuz-dirsek', '/site/img/service-omuz-dirsek.jpg', 'index'),
('service-artroskopi', '/site/img/service-artroskopi.jpg', 'index'),
('service-diz-kalca', '/site/img/service-diz-kalca.jpg', 'index'),
('service-protez', '/site/img/service-protez.jpg', 'index'),
('dr-taha-office', '/site/img/dr-taha-office.jpg', 'index'),
('dr-taha-hero-user', '/__l5e/assets-v1/b116cb68-084f-4fc4-b227-a11d44a29c3e/dr-taha-hero-2026.png', 'index'),
('ortho-2', '/site/img/ortho-2.jpg', 'gallery'),
('ortho-1', '/site/img/ortho-1.jpg', 'gallery'),
('ortho-4', '/site/img/ortho-4.jpg', 'gallery'),
('ortho-3', '/site/img/ortho-3.jpg', 'gallery')
ON CONFLICT (slot) DO NOTHING;

INSERT INTO public.site_pages (slug, path, title_key, description_key, keywords_key, sort_order) VALUES
('index', '/site/index.html', 't_w8u4oz18xebos', 't_bo9o271tku3ir', 't_1vmzqdi606cds', 0),
('about', '/site/about.html', 't_1flhg57oaxt8q', 't_1m65dd0v1iiki', 't_1ulbqx51valuz8', 1),
('service', '/site/service.html', 't_15hxswbwmom6j', 't_0z24vc32qhbcl', 't_1f3bfahrw0egk', 2),
('gallery', '/site/gallery.html', 't_00ppwmux53rdb', 't_07thjtp7krl9b', 't_9znql21ymrote', 3),
('appoinment', '/site/appoinment.html', 't_1qw5jnc93ue99', 't_03dg52fm3qcu6', 't_0ftiqeebrx5ma', 4),
('contact', '/site/contact.html', 't_0dobl7si8f3gr', 't_0aht863xdrw73', 't_p2p01k1wkbv3r', 5)
ON CONFLICT (slug) DO NOTHING;
